//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines the addresses for a call.
 * 
 *         Introduced: Version 1.0, Compatibility Level 8.
 *       
 * 
 * <p>Java class for AddressesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddressesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SigAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MediaIPAddr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MediaPort" type="{http://www.metaswitch.com/cfs/billing/V1.0}PortType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddressesType", propOrder = {
    "sigAddress",
    "mediaIPAddr",
    "mediaPort"
})
public class AddressesType {

    @XmlElement(name = "SigAddress")
    protected String sigAddress;
    @XmlElement(name = "MediaIPAddr")
    protected String mediaIPAddr;
    @XmlElement(name = "MediaPort")
    protected Integer mediaPort;

    /**
     * Gets the value of the sigAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSigAddress() {
        return sigAddress;
    }

    /**
     * Sets the value of the sigAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSigAddress(String value) {
        this.sigAddress = value;
    }

    /**
     * Gets the value of the mediaIPAddr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMediaIPAddr() {
        return mediaIPAddr;
    }

    /**
     * Sets the value of the mediaIPAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMediaIPAddr(String value) {
        this.mediaIPAddr = value;
    }

    /**
     * Gets the value of the mediaPort property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMediaPort() {
        return mediaPort;
    }

    /**
     * Sets the value of the mediaPort property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMediaPort(Integer value) {
        this.mediaPort = value;
    }

}
