//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This value represents the Called Party Category of a party
 *         in an ISUP call.
 * 
 *         Introduced: Version 1.0, Compatibility Level 7.
 *       
 * 
 * <p>Java class for CalledPartyNumCat complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CalledPartyNumCat">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Sent" type="{http://www.metaswitch.com/cfs/billing/V1.0}CalledPartyNumCatType" minOccurs="0"/>
 *         &lt;element name="Recv" type="{http://www.metaswitch.com/cfs/billing/V1.0}CalledPartyNumCatType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CalledPartyNumCat", propOrder = {
    "sent",
    "recv"
})
public class CalledPartyNumCat {

    @XmlElement(name = "Sent")
    protected CalledPartyNumCatType sent;
    @XmlElement(name = "Recv")
    protected CalledPartyNumCatType recv;

    /**
     * Gets the value of the sent property.
     * 
     * @return
     *     possible object is
     *     {@link CalledPartyNumCatType }
     *     
     */
    public CalledPartyNumCatType getSent() {
        return sent;
    }

    /**
     * Sets the value of the sent property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalledPartyNumCatType }
     *     
     */
    public void setSent(CalledPartyNumCatType value) {
        this.sent = value;
    }

    /**
     * Gets the value of the recv property.
     * 
     * @return
     *     possible object is
     *     {@link CalledPartyNumCatType }
     *     
     */
    public CalledPartyNumCatType getRecv() {
        return recv;
    }

    /**
     * Sets the value of the recv property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalledPartyNumCatType }
     *     
     */
    public void setRecv(CalledPartyNumCatType value) {
        this.recv = value;
    }

}
