//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This value represents the value of the Call Reference
 *         parameter signalled in an ISUP call.
 * 
 *         Introduced: Version 1.0, Compatibility Level 7.
 *       
 * 
 * <p>Java class for CallReferenceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CallReferenceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PointCode" type="{http://www.metaswitch.com/cfs/billing/V1.0}PointCodeDecimalType" minOccurs="0"/>
 *         &lt;element name="CallIdentity" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CallReferenceType", propOrder = {
    "pointCode",
    "callIdentity"
})
public class CallReferenceType {

    @XmlElement(name = "PointCode")
    protected String pointCode;
    @XmlElement(name = "CallIdentity")
    protected Integer callIdentity;

    /**
     * Gets the value of the pointCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPointCode() {
        return pointCode;
    }

    /**
     * Sets the value of the pointCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPointCode(String value) {
        this.pointCode = value;
    }

    /**
     * Gets the value of the callIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCallIdentity() {
        return callIdentity;
    }

    /**
     * Sets the value of the callIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCallIdentity(Integer value) {
        this.callIdentity = value;
    }

}
