//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CalledPartyNumCatType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CalledPartyNumCatType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="No Indication"/>
 *     &lt;enumeration value="Ordinary Subscriber"/>
 *     &lt;enumeration value="Payphone"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CalledPartyNumCatType")
@XmlEnum
public enum CalledPartyNumCatType {


    /**
     * No indication of called party category.
     *           
     * 
     */
    @XmlEnumValue("No Indication")
    NO_INDICATION("No Indication"),

    /**
     * The called party is an ordinary subscriber.
     *           
     * 
     */
    @XmlEnumValue("Ordinary Subscriber")
    ORDINARY_SUBSCRIBER("Ordinary Subscriber"),

    /**
     * The called party is a payphone.
     *           
     * 
     */
    @XmlEnumValue("Payphone")
    PAYPHONE("Payphone");
    private final String value;

    CalledPartyNumCatType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CalledPartyNumCatType fromValue(String v) {
        for (CalledPartyNumCatType c: CalledPartyNumCatType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
