//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Specifies the details of the call-forwarding treatment of
 *         a call.
 *       
 * 
 * <p>Java class for CallForwardInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CallForwardInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OriginalCallingAddr" type="{http://www.metaswitch.com/cfs/billing/V1.0}AddressType" minOccurs="0"/>
 *         &lt;element name="OriginalCalledAddr" type="{http://www.metaswitch.com/cfs/billing/V1.0}AddressType" minOccurs="0"/>
 *         &lt;element name="LastRedirectingAddr" type="{http://www.metaswitch.com/cfs/billing/V1.0}AddressType" minOccurs="0"/>
 *         &lt;element name="RedirectCount" type="{http://www.w3.org/2001/XMLSchema}unsignedShort"/>
 *         &lt;element name="RedirectReason" type="{http://www.metaswitch.com/cfs/billing/V1.0}RedirectReasonType" minOccurs="0"/>
 *         &lt;element name="OriginalRedirectReason" type="{http://www.metaswitch.com/cfs/billing/V1.0}RedirectReasonType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="privacy" use="required" type="{http://www.metaswitch.com/cfs/billing/V1.0}PrivacyType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CallForwardInfoType", propOrder = {
    "originalCallingAddr",
    "originalCalledAddr",
    "lastRedirectingAddr",
    "redirectCount",
    "redirectReason",
    "originalRedirectReason"
})
public class CallForwardInfoType {

    @XmlElement(name = "OriginalCallingAddr")
    protected AddressType originalCallingAddr;
    @XmlElement(name = "OriginalCalledAddr")
    protected AddressType originalCalledAddr;
    @XmlElement(name = "LastRedirectingAddr")
    protected AddressType lastRedirectingAddr;
    @XmlElement(name = "RedirectCount")
    @XmlSchemaType(name = "unsignedShort")
    protected int redirectCount;
    @XmlElement(name = "RedirectReason")
    protected RedirectReasonType redirectReason;
    @XmlElement(name = "OriginalRedirectReason")
    protected RedirectReasonType originalRedirectReason;
    @XmlAttribute(name = "privacy", required = true)
    protected PrivacyType privacy;

    /**
     * Gets the value of the originalCallingAddr property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getOriginalCallingAddr() {
        return originalCallingAddr;
    }

    /**
     * Sets the value of the originalCallingAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setOriginalCallingAddr(AddressType value) {
        this.originalCallingAddr = value;
    }

    /**
     * Gets the value of the originalCalledAddr property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getOriginalCalledAddr() {
        return originalCalledAddr;
    }

    /**
     * Sets the value of the originalCalledAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setOriginalCalledAddr(AddressType value) {
        this.originalCalledAddr = value;
    }

    /**
     * Gets the value of the lastRedirectingAddr property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getLastRedirectingAddr() {
        return lastRedirectingAddr;
    }

    /**
     * Sets the value of the lastRedirectingAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setLastRedirectingAddr(AddressType value) {
        this.lastRedirectingAddr = value;
    }

    /**
     * Gets the value of the redirectCount property.
     * 
     */
    public int getRedirectCount() {
        return redirectCount;
    }

    /**
     * Sets the value of the redirectCount property.
     * 
     */
    public void setRedirectCount(int value) {
        this.redirectCount = value;
    }

    /**
     * Gets the value of the redirectReason property.
     * 
     * @return
     *     possible object is
     *     {@link RedirectReasonType }
     *     
     */
    public RedirectReasonType getRedirectReason() {
        return redirectReason;
    }

    /**
     * Sets the value of the redirectReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link RedirectReasonType }
     *     
     */
    public void setRedirectReason(RedirectReasonType value) {
        this.redirectReason = value;
    }

    /**
     * Gets the value of the originalRedirectReason property.
     * 
     * @return
     *     possible object is
     *     {@link RedirectReasonType }
     *     
     */
    public RedirectReasonType getOriginalRedirectReason() {
        return originalRedirectReason;
    }

    /**
     * Sets the value of the originalRedirectReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link RedirectReasonType }
     *     
     */
    public void setOriginalRedirectReason(RedirectReasonType value) {
        this.originalRedirectReason = value;
    }

    /**
     * Gets the value of the privacy property.
     * 
     * @return
     *     possible object is
     *     {@link PrivacyType }
     *     
     */
    public PrivacyType getPrivacy() {
        return privacy;
    }

    /**
     * Sets the value of the privacy property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrivacyType }
     *     
     */
    public void setPrivacy(PrivacyType value) {
        this.privacy = value;
    }

}
