//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Specifies the details representing one leg of a call.
 *       
 * 
 * <p>Java class for CallType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CallType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CallType" type="{http://www.metaswitch.com/cfs/billing/V1.0}CallTypeType"/>
 *         &lt;element name="Features" type="{http://www.metaswitch.com/cfs/billing/V1.0}FeaturesType" minOccurs="0"/>
 *         &lt;element name="ReleasingParty" type="{http://www.metaswitch.com/cfs/billing/V1.0}ReleasingPartyType" minOccurs="0"/>
 *         &lt;element name="ReleaseReason" type="{http://www.metaswitch.com/cfs/billing/V1.0}ReleaseReasonType" maxOccurs="3" minOccurs="0"/>
 *         &lt;element name="InternalIndex" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="OrigParty" type="{http://www.metaswitch.com/cfs/billing/V1.0}PartyType"/>
 *         &lt;element name="TermParty" type="{http://www.metaswitch.com/cfs/billing/V1.0}PartyType"/>
 *         &lt;element name="RoutingInfo" type="{http://www.metaswitch.com/cfs/billing/V1.0}RoutingInfoType"/>
 *         &lt;element name="CarrierSelectInfo" type="{http://www.metaswitch.com/cfs/billing/V1.0}CarrierSelectInfoType" minOccurs="0"/>
 *         &lt;element name="CallForwardInfo" type="{http://www.metaswitch.com/cfs/billing/V1.0}CallForwardInfoType" minOccurs="0"/>
 *         &lt;element name="NPInfo" type="{http://www.metaswitch.com/cfs/billing/V1.0}NPInfoType" maxOccurs="2" minOccurs="0"/>
 *         &lt;element name="IntelligentNetworkInfo" type="{http://www.metaswitch.com/cfs/billing/V1.0}IntelligentNetworkInfoType" minOccurs="0"/>
 *         &lt;element name="AccountCodeInfo" type="{http://www.metaswitch.com/cfs/billing/V1.0}AccountCodeInfoType" minOccurs="0"/>
 *         &lt;element name="CustomerInfo" type="{http://www.metaswitch.com/cfs/billing/V1.0}CustomerCodeType" minOccurs="0"/>
 *         &lt;element name="SignalingInfo" type="{http://www.metaswitch.com/cfs/billing/V1.0}SignalingInfoType" minOccurs="0"/>
 *         &lt;element name="MessageBillingIndex" type="{http://www.metaswitch.com/cfs/billing/V1.0}MessageBillingIndexType" minOccurs="0"/>
 *         &lt;element name="IcSeizeTime" type="{http://www.metaswitch.com/cfs/billing/V1.0}TimestampType" minOccurs="0"/>
 *         &lt;element name="OgSeizeTime" type="{http://www.metaswitch.com/cfs/billing/V1.0}TimestampType"/>
 *         &lt;element name="RingingTime" type="{http://www.metaswitch.com/cfs/billing/V1.0}TimestampType" minOccurs="0"/>
 *         &lt;element name="ConnectTime" type="{http://www.metaswitch.com/cfs/billing/V1.0}TimestampType"/>
 *         &lt;element name="DisconnectTime" type="{http://www.metaswitch.com/cfs/billing/V1.0}TimestampType" minOccurs="0"/>
 *         &lt;element name="PostDialDelay" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="PGRD" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="PGAD" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="ReleaseTime" type="{http://www.metaswitch.com/cfs/billing/V1.0}TimestampType"/>
 *         &lt;element name="CompleteTime" type="{http://www.metaswitch.com/cfs/billing/V1.0}TimestampType" minOccurs="0"/>
 *         &lt;element name="LongDurationInfo" type="{http://www.metaswitch.com/cfs/billing/V1.0}LongDurationInfoType" minOccurs="0"/>
 *         &lt;element name="UDAs" type="{http://www.metaswitch.com/cfs/billing/V1.0}UDAsType" minOccurs="0"/>
 *         &lt;element name="IncomingGateway" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OutgoingGateway" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ReleaseCause" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="SIPIBodyReleaseCause" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="seqnum" use="required" type="{http://www.metaswitch.com/cfs/billing/V1.0}CDRSeqNumType" />
 *       &lt;attribute name="error" type="{http://www.metaswitch.com/cfs/billing/V1.0}ErrorType" default="no" />
 *       &lt;attribute name="connected" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="reestablished" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="correlator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}long" default="0" />
 *       &lt;attribute name="testcall" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="operator" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="longcall" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CallType", propOrder = {
    "callType",
    "features",
    "releasingParty",
    "releaseReason",
    "internalIndex",
    "origParty",
    "termParty",
    "routingInfo",
    "carrierSelectInfo",
    "callForwardInfo",
    "npInfo",
    "intelligentNetworkInfo",
    "accountCodeInfo",
    "customerInfo",
    "signalingInfo",
    "messageBillingIndex",
    "icSeizeTime",
    "ogSeizeTime",
    "ringingTime",
    "connectTime",
    "disconnectTime",
    "postDialDelay",
    "pgrd",
    "pgad",
    "releaseTime",
    "completeTime",
    "longDurationInfo",
    "udAs",
    "incomingGateway",
    "outgoingGateway",
    "releaseCause",
    "sipiBodyReleaseCause"
})
public class CallType {

    @XmlElement(name = "CallType", required = true)
    protected CallTypeType callType;
    @XmlElement(name = "Features")
    protected FeaturesType features;
    @XmlElement(name = "ReleasingParty")
    protected ReleasingPartyType releasingParty;
    @XmlElement(name = "ReleaseReason")
    protected List<ReleaseReasonType> releaseReason;
    @XmlElement(name = "InternalIndex")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger internalIndex;
    @XmlElement(name = "OrigParty", required = true)
    protected PartyType origParty;
    @XmlElement(name = "TermParty", required = true)
    protected PartyType termParty;
    @XmlElement(name = "RoutingInfo", required = true)
    protected RoutingInfoType routingInfo;
    @XmlElement(name = "CarrierSelectInfo")
    protected CarrierSelectInfoType carrierSelectInfo;
    @XmlElement(name = "CallForwardInfo")
    protected CallForwardInfoType callForwardInfo;
    @XmlElement(name = "NPInfo")
    protected List<NPInfoType> npInfo;
    @XmlElement(name = "IntelligentNetworkInfo")
    protected IntelligentNetworkInfoType intelligentNetworkInfo;
    @XmlElement(name = "AccountCodeInfo")
    protected String accountCodeInfo;
    @XmlElement(name = "CustomerInfo")
    protected CustomerCodeType customerInfo;
    @XmlElement(name = "SignalingInfo")
    protected SignalingInfoType signalingInfo;
    @XmlElement(name = "MessageBillingIndex")
    protected Integer messageBillingIndex;
    @XmlElement(name = "IcSeizeTime")
    protected String icSeizeTime;
    @XmlElement(name = "OgSeizeTime", required = true)
    protected String ogSeizeTime;
    @XmlElement(name = "RingingTime")
    protected String ringingTime;
    @XmlElement(name = "ConnectTime", required = true)
    protected String connectTime;
    @XmlElement(name = "DisconnectTime")
    protected String disconnectTime;
    @XmlElement(name = "PostDialDelay")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger postDialDelay;
    @XmlElement(name = "PGRD")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger pgrd;
    @XmlElement(name = "PGAD")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger pgad;
    @XmlElement(name = "ReleaseTime", required = true)
    protected String releaseTime;
    @XmlElement(name = "CompleteTime")
    protected String completeTime;
    @XmlElement(name = "LongDurationInfo")
    protected LongDurationInfoType longDurationInfo;
    @XmlElement(name = "UDAs")
    protected UDAsType udAs;
    @XmlElement(name = "IncomingGateway")
    protected String incomingGateway;
    @XmlElement(name = "OutgoingGateway")
    protected String outgoingGateway;
    @XmlElement(name = "ReleaseCause")
    protected Integer releaseCause;
    @XmlElement(name = "SIPIBodyReleaseCause")
    protected Integer sipiBodyReleaseCause;
    @XmlAttribute(name = "seqnum", required = true)
    protected int seqnum;
    @XmlAttribute(name = "error")
    protected ErrorType error;
    @XmlAttribute(name = "connected")
    protected Boolean connected;
    @XmlAttribute(name = "reestablished")
    protected Boolean reestablished;
    @XmlAttribute(name = "correlator")
    protected String correlator;
    @XmlAttribute(name = "class")
    protected Long clazz;
    @XmlAttribute(name = "testcall")
    protected Boolean testcall;
    @XmlAttribute(name = "operator")
    protected Boolean operator;
    @XmlAttribute(name = "longcall")
    protected Boolean longcall;

    /**
     * Gets the value of the callType property.
     * 
     * @return
     *     possible object is
     *     {@link CallTypeType }
     *     
     */
    public CallTypeType getCallType() {
        return callType;
    }

    /**
     * Sets the value of the callType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CallTypeType }
     *     
     */
    public void setCallType(CallTypeType value) {
        this.callType = value;
    }

    /**
     * Gets the value of the features property.
     * 
     * @return
     *     possible object is
     *     {@link FeaturesType }
     *     
     */
    public FeaturesType getFeatures() {
        return features;
    }

    /**
     * Sets the value of the features property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeaturesType }
     *     
     */
    public void setFeatures(FeaturesType value) {
        this.features = value;
    }

    /**
     * Gets the value of the releasingParty property.
     * 
     * @return
     *     possible object is
     *     {@link ReleasingPartyType }
     *     
     */
    public ReleasingPartyType getReleasingParty() {
        return releasingParty;
    }

    /**
     * Sets the value of the releasingParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReleasingPartyType }
     *     
     */
    public void setReleasingParty(ReleasingPartyType value) {
        this.releasingParty = value;
    }

    /**
     * Gets the value of the releaseReason property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the releaseReason property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReleaseReason().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReleaseReasonType }
     * 
     * 
     */
    public List<ReleaseReasonType> getReleaseReason() {
        if (releaseReason == null) {
            releaseReason = new ArrayList<ReleaseReasonType>();
        }
        return this.releaseReason;
    }

    /**
     * Gets the value of the internalIndex property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getInternalIndex() {
        return internalIndex;
    }

    /**
     * Sets the value of the internalIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setInternalIndex(BigInteger value) {
        this.internalIndex = value;
    }

    /**
     * Gets the value of the origParty property.
     * 
     * @return
     *     possible object is
     *     {@link PartyType }
     *     
     */
    public PartyType getOrigParty() {
        return origParty;
    }

    /**
     * Sets the value of the origParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyType }
     *     
     */
    public void setOrigParty(PartyType value) {
        this.origParty = value;
    }

    /**
     * Gets the value of the termParty property.
     * 
     * @return
     *     possible object is
     *     {@link PartyType }
     *     
     */
    public PartyType getTermParty() {
        return termParty;
    }

    /**
     * Sets the value of the termParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyType }
     *     
     */
    public void setTermParty(PartyType value) {
        this.termParty = value;
    }

    /**
     * Gets the value of the routingInfo property.
     * 
     * @return
     *     possible object is
     *     {@link RoutingInfoType }
     *     
     */
    public RoutingInfoType getRoutingInfo() {
        return routingInfo;
    }

    /**
     * Sets the value of the routingInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoutingInfoType }
     *     
     */
    public void setRoutingInfo(RoutingInfoType value) {
        this.routingInfo = value;
    }

    /**
     * Gets the value of the carrierSelectInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CarrierSelectInfoType }
     *     
     */
    public CarrierSelectInfoType getCarrierSelectInfo() {
        return carrierSelectInfo;
    }

    /**
     * Sets the value of the carrierSelectInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarrierSelectInfoType }
     *     
     */
    public void setCarrierSelectInfo(CarrierSelectInfoType value) {
        this.carrierSelectInfo = value;
    }

    /**
     * Gets the value of the callForwardInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CallForwardInfoType }
     *     
     */
    public CallForwardInfoType getCallForwardInfo() {
        return callForwardInfo;
    }

    /**
     * Sets the value of the callForwardInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CallForwardInfoType }
     *     
     */
    public void setCallForwardInfo(CallForwardInfoType value) {
        this.callForwardInfo = value;
    }

    /**
     * Gets the value of the npInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the npInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNPInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NPInfoType }
     * 
     * 
     */
    public List<NPInfoType> getNPInfo() {
        if (npInfo == null) {
            npInfo = new ArrayList<NPInfoType>();
        }
        return this.npInfo;
    }

    /**
     * Gets the value of the intelligentNetworkInfo property.
     * 
     * @return
     *     possible object is
     *     {@link IntelligentNetworkInfoType }
     *     
     */
    public IntelligentNetworkInfoType getIntelligentNetworkInfo() {
        return intelligentNetworkInfo;
    }

    /**
     * Sets the value of the intelligentNetworkInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntelligentNetworkInfoType }
     *     
     */
    public void setIntelligentNetworkInfo(IntelligentNetworkInfoType value) {
        this.intelligentNetworkInfo = value;
    }

    /**
     * Gets the value of the accountCodeInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountCodeInfo() {
        return accountCodeInfo;
    }

    /**
     * Sets the value of the accountCodeInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountCodeInfo(String value) {
        this.accountCodeInfo = value;
    }

    /**
     * Gets the value of the customerInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerCodeType }
     *     
     */
    public CustomerCodeType getCustomerInfo() {
        return customerInfo;
    }

    /**
     * Sets the value of the customerInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerCodeType }
     *     
     */
    public void setCustomerInfo(CustomerCodeType value) {
        this.customerInfo = value;
    }

    /**
     * Gets the value of the signalingInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SignalingInfoType }
     *     
     */
    public SignalingInfoType getSignalingInfo() {
        return signalingInfo;
    }

    /**
     * Sets the value of the signalingInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignalingInfoType }
     *     
     */
    public void setSignalingInfo(SignalingInfoType value) {
        this.signalingInfo = value;
    }

    /**
     * Gets the value of the messageBillingIndex property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMessageBillingIndex() {
        return messageBillingIndex;
    }

    /**
     * Sets the value of the messageBillingIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMessageBillingIndex(Integer value) {
        this.messageBillingIndex = value;
    }

    /**
     * Gets the value of the icSeizeTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIcSeizeTime() {
        return icSeizeTime;
    }

    /**
     * Sets the value of the icSeizeTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIcSeizeTime(String value) {
        this.icSeizeTime = value;
    }

    /**
     * Gets the value of the ogSeizeTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOgSeizeTime() {
        return ogSeizeTime;
    }

    /**
     * Sets the value of the ogSeizeTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOgSeizeTime(String value) {
        this.ogSeizeTime = value;
    }

    /**
     * Gets the value of the ringingTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRingingTime() {
        return ringingTime;
    }

    /**
     * Sets the value of the ringingTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRingingTime(String value) {
        this.ringingTime = value;
    }

    /**
     * Gets the value of the connectTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnectTime() {
        return connectTime;
    }

    /**
     * Sets the value of the connectTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnectTime(String value) {
        this.connectTime = value;
    }

    /**
     * Gets the value of the disconnectTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisconnectTime() {
        return disconnectTime;
    }

    /**
     * Sets the value of the disconnectTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisconnectTime(String value) {
        this.disconnectTime = value;
    }

    /**
     * Gets the value of the postDialDelay property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPostDialDelay() {
        return postDialDelay;
    }

    /**
     * Sets the value of the postDialDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPostDialDelay(BigInteger value) {
        this.postDialDelay = value;
    }

    /**
     * Gets the value of the pgrd property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPGRD() {
        return pgrd;
    }

    /**
     * Sets the value of the pgrd property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPGRD(BigInteger value) {
        this.pgrd = value;
    }

    /**
     * Gets the value of the pgad property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPGAD() {
        return pgad;
    }

    /**
     * Sets the value of the pgad property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPGAD(BigInteger value) {
        this.pgad = value;
    }

    /**
     * Gets the value of the releaseTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReleaseTime() {
        return releaseTime;
    }

    /**
     * Sets the value of the releaseTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReleaseTime(String value) {
        this.releaseTime = value;
    }

    /**
     * Gets the value of the completeTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompleteTime() {
        return completeTime;
    }

    /**
     * Sets the value of the completeTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompleteTime(String value) {
        this.completeTime = value;
    }

    /**
     * Gets the value of the longDurationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LongDurationInfoType }
     *     
     */
    public LongDurationInfoType getLongDurationInfo() {
        return longDurationInfo;
    }

    /**
     * Sets the value of the longDurationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LongDurationInfoType }
     *     
     */
    public void setLongDurationInfo(LongDurationInfoType value) {
        this.longDurationInfo = value;
    }

    /**
     * Gets the value of the udAs property.
     * 
     * @return
     *     possible object is
     *     {@link UDAsType }
     *     
     */
    public UDAsType getUDAs() {
        return udAs;
    }

    /**
     * Sets the value of the udAs property.
     * 
     * @param value
     *     allowed object is
     *     {@link UDAsType }
     *     
     */
    public void setUDAs(UDAsType value) {
        this.udAs = value;
    }

    /**
     * Gets the value of the incomingGateway property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIncomingGateway() {
        return incomingGateway;
    }

    /**
     * Sets the value of the incomingGateway property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIncomingGateway(String value) {
        this.incomingGateway = value;
    }

    /**
     * Gets the value of the outgoingGateway property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutgoingGateway() {
        return outgoingGateway;
    }

    /**
     * Sets the value of the outgoingGateway property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutgoingGateway(String value) {
        this.outgoingGateway = value;
    }

    /**
     * Gets the value of the releaseCause property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getReleaseCause() {
        return releaseCause;
    }

    /**
     * Sets the value of the releaseCause property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setReleaseCause(Integer value) {
        this.releaseCause = value;
    }

    /**
     * Gets the value of the sipiBodyReleaseCause property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSIPIBodyReleaseCause() {
        return sipiBodyReleaseCause;
    }

    /**
     * Sets the value of the sipiBodyReleaseCause property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSIPIBodyReleaseCause(Integer value) {
        this.sipiBodyReleaseCause = value;
    }

    /**
     * Gets the value of the seqnum property.
     * 
     */
    public int getSeqnum() {
        return seqnum;
    }

    /**
     * Sets the value of the seqnum property.
     * 
     */
    public void setSeqnum(int value) {
        this.seqnum = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorType }
     *     
     */
    public ErrorType getError() {
        if (error == null) {
            return ErrorType.NO;
        } else {
            return error;
        }
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorType }
     *     
     */
    public void setError(ErrorType value) {
        this.error = value;
    }

    /**
     * Gets the value of the connected property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isConnected() {
        if (connected == null) {
            return false;
        } else {
            return connected;
        }
    }

    /**
     * Sets the value of the connected property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setConnected(Boolean value) {
        this.connected = value;
    }

    /**
     * Gets the value of the reestablished property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isReestablished() {
        if (reestablished == null) {
            return false;
        } else {
            return reestablished;
        }
    }

    /**
     * Sets the value of the reestablished property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReestablished(Boolean value) {
        this.reestablished = value;
    }

    /**
     * Gets the value of the correlator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrelator() {
        return correlator;
    }

    /**
     * Sets the value of the correlator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrelator(String value) {
        this.correlator = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getClazz() {
        if (clazz == null) {
            return  0L;
        } else {
            return clazz;
        }
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setClazz(Long value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the testcall property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isTestcall() {
        if (testcall == null) {
            return false;
        } else {
            return testcall;
        }
    }

    /**
     * Sets the value of the testcall property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTestcall(Boolean value) {
        this.testcall = value;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isOperator() {
        if (operator == null) {
            return false;
        } else {
            return operator;
        }
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOperator(Boolean value) {
        this.operator = value;
    }

    /**
     * Gets the value of the longcall property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isLongcall() {
        if (longcall == null) {
            return false;
        } else {
            return longcall;
        }
    }

    /**
     * Sets the value of the longcall property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setLongcall(Boolean value) {
        this.longcall = value;
    }

}
