//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CallTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CallTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Local"/>
 *     &lt;enumeration value="National"/>
 *     &lt;enumeration value="International"/>
 *     &lt;enumeration value="Unknown"/>
 *     &lt;enumeration value="Broadband"/>
 *     &lt;enumeration value="Corporate"/>
 *     &lt;enumeration value="DirectoryAssistance"/>
 *     &lt;enumeration value="Emergency"/>
 *     &lt;enumeration value="LocalNonGeographic"/>
 *     &lt;enumeration value="Mobile"/>
 *     &lt;enumeration value="NationalNonGeographic"/>
 *     &lt;enumeration value="Operator"/>
 *     &lt;enumeration value="OtherCarrier"/>
 *     &lt;enumeration value="Paging"/>
 *     &lt;enumeration value="PersonalNumber"/>
 *     &lt;enumeration value="Premium"/>
 *     &lt;enumeration value="TollFree"/>
 *     &lt;enumeration value="Other"/>
 *     &lt;enumeration value="IntraLATA"/>
 *     &lt;enumeration value="InterLATANational"/>
 *     &lt;enumeration value="InterLATAInternational"/>
 *     &lt;enumeration value="OtherNonGeographic"/>
 *     &lt;enumeration value="CarrierCutThrough"/>
 *     &lt;enumeration value="FeatureGroupB"/>
 *     &lt;enumeration value="InternationalTollFree"/>
 *     &lt;enumeration value="OtherN11"/>
 *     &lt;enumeration value="CorporateTollFree"/>
 *     &lt;enumeration value="Repair"/>
 *     &lt;enumeration value="ConferenceBridge"/>
 *     &lt;enumeration value="ANIService"/>
 *     &lt;enumeration value="CLASSFeature"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CallTypeType")
@XmlEnum
public enum CallTypeType {


    /**
     * A local call (valid ETSI and Telcordia)
     *           
     * 
     */
    @XmlEnumValue("Local")
    LOCAL("Local"),

    /**
     * A national call (valid ETSI only)
     *           
     * 
     */
    @XmlEnumValue("National")
    NATIONAL("National"),

    /**
     * An international call (valid ETSI and Telcordia)
     *           
     * 
     */
    @XmlEnumValue("International")
    INTERNATIONAL("International"),

    /**
     * The type of call is unknown (valid ETSI and Telcordia)
     *           
     * 
     */
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown"),

    /**
     * A broadband (i.e. VoIP) call (valid ETSI only)
     *           
     * 
     */
    @XmlEnumValue("Broadband")
    BROADBAND("Broadband"),

    /**
     * A call to a corporate (i.e. non-geographic) number
     *              (valid ETSI only)
     *           
     * 
     */
    @XmlEnumValue("Corporate")
    CORPORATE("Corporate"),

    /**
     * A call to a directory-assistance (enquiries) number
     *             (valid ETSI and Telcordia)
     *           
     * 
     */
    @XmlEnumValue("DirectoryAssistance")
    DIRECTORY_ASSISTANCE("DirectoryAssistance"),

    /**
     * A call to emergency services (valid ETSI and
     *             Telcordia)
     *           
     * 
     */
    @XmlEnumValue("Emergency")
    EMERGENCY("Emergency"),

    /**
     * A call to a non-geographic number which is charged at
     *             local rates (valid ETSI only)
     * 
     */
    @XmlEnumValue("LocalNonGeographic")
    LOCAL_NON_GEOGRAPHIC("LocalNonGeographic"),

    /**
     * A call to a mobile number (valid ETSI only)
     *           
     * 
     */
    @XmlEnumValue("Mobile")
    MOBILE("Mobile"),

    /**
     * A call to a non-geographic number which is charged at
     *             national rates (valid ETSI only)
     *           
     * 
     */
    @XmlEnumValue("NationalNonGeographic")
    NATIONAL_NON_GEOGRAPHIC("NationalNonGeographic"),

    /**
     * A call to operator-services (valid ETSI and Telcordia)
     *           
     * 
     */
    @XmlEnumValue("Operator")
    OPERATOR("Operator"),

    /**
     * An indirect access call to another carrier (valid ETSI
     *             only)
     *           
     * 
     */
    @XmlEnumValue("OtherCarrier")
    OTHER_CARRIER("OtherCarrier"),

    /**
     * A call to a paging service (valid ETSI only)
     *           
     * 
     */
    @XmlEnumValue("Paging")
    PAGING("Paging"),

    /**
     * A call to a personal-number service (valid ETSI only)
     *           
     * 
     */
    @XmlEnumValue("PersonalNumber")
    PERSONAL_NUMBER("PersonalNumber"),

    /**
     * A call to a non-geographic number which is charged at
     *             a premium rate (valid ETSI and Telcordia)
     *           
     * 
     */
    @XmlEnumValue("Premium")
    PREMIUM("Premium"),

    /**
     * A call to a non-geographic number which is not charged
     *             to the caller (valid ETSI and Telcordia)
     *           
     * 
     */
    @XmlEnumValue("TollFree")
    TOLL_FREE("TollFree"),

    /**
     * An unspecified other type of call (valid ETSI and
     *             Telcordia)
     *           
     * 
     */
    @XmlEnumValue("Other")
    OTHER("Other"),

    /**
     * A call within a LATA (valid Telcordia only)
     *           
     * 
     */
    @XmlEnumValue("IntraLATA")
    INTRA_LATA("IntraLATA"),

    /**
     * A national call between LATAs (valid Telcordia only)
     *           
     * 
     */
    @XmlEnumValue("InterLATANational")
    INTER_LATA_NATIONAL("InterLATANational"),

    /**
     * An international call between LATAs (valid Telcordia
     *             only)
     *           
     * 
     */
    @XmlEnumValue("InterLATAInternational")
    INTER_LATA_INTERNATIONAL("InterLATAInternational"),

    /**
     * A non-geographic call not fitting into the other
     *             categories (valid Telcordia only)
     *           
     * 
     */
    @XmlEnumValue("OtherNonGeographic")
    OTHER_NON_GEOGRAPHIC("OtherNonGeographic"),

    /**
     * A carrier cut-through call (valid Telcordia only)
     *           
     * 
     */
    @XmlEnumValue("CarrierCutThrough")
    CARRIER_CUT_THROUGH("CarrierCutThrough"),

    /**
     * A Feature Group B call (valid Telcordia only)
     *           
     * 
     */
    @XmlEnumValue("FeatureGroupB")
    FEATURE_GROUP_B("FeatureGroupB"),

    /**
     * A call to an international non-geographic number which
     *             is not charged to the caller (valid Telcordia only)
     *           
     * 
     */
    @XmlEnumValue("InternationalTollFree")
    INTERNATIONAL_TOLL_FREE("InternationalTollFree"),

    /**
     * A call to an N11 service not fitting into one of the
     *             other categories (valid Telcordia only)
     *           
     * 
     */
    @XmlEnumValue("OtherN11")
    OTHER_N_11("OtherN11"),

    /**
     * A call to a non-geographic number representing a
     *             corporation which is not charged to the caller (valid ETSI only)
     *           
     * 
     */
    @XmlEnumValue("CorporateTollFree")
    CORPORATE_TOLL_FREE("CorporateTollFree"),

    /**
     * A call to a repair-service helpdesk within the
     *             network operator's business (valid Telcordia only)
     *           
     * 
     */
    @XmlEnumValue("Repair")
    REPAIR("Repair"),

    /**
     * A call to a conference bridge (valid ETSI and
     *             Telcordia). This is a "pseudo-value" set by a service and not in
     *             Number Validation.
     *           
     * 
     */
    @XmlEnumValue("ConferenceBridge")
    CONFERENCE_BRIDGE("ConferenceBridge"),

    /**
     * A call to a service that authorizes users to make
     *             calls based on their calling party number (e.g. indirect access
     *             services) (valid ETSI and Telcordia). This is a "pseudo-value" set
     *             by a service and not in Number Validation.
     *           
     * 
     */
    @XmlEnumValue("ANIService")
    ANI_SERVICE("ANIService"),

    /**
     * A call that represents a CLASS service (valid ETSI and
     *             Telcordia). This is a "pseudo-value" set by a service and not in
     *             Number Validation.
     *           
     * 
     */
    @XmlEnumValue("CLASSFeature")
    CLASS_FEATURE("CLASSFeature");
    private final String value;

    CallTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CallTypeType fromValue(String v) {
        for (CallTypeType c: CallTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
