//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CarrierOperatorType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CarrierOperatorType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="False"/>
 *     &lt;enumeration value="True"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CarrierOperatorType")
@XmlEnum
public enum CarrierOperatorType {


    /**
     * The Carrier's operator was not involved.
     *           
     * 
     */
    @XmlEnumValue("False")
    FALSE("False"),

    /**
     * The Carrier's operator was involved.
     *           
     * 
     */
    @XmlEnumValue("True")
    TRUE("True");
    private final String value;

    CarrierOperatorType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CarrierOperatorType fromValue(String v) {
        for (CarrierOperatorType c: CarrierOperatorType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
