//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Specifies information about the carrier-selection
 *         undertaken during the handling of this call.
 *       
 * 
 * <p>Java class for CarrierSelectInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CarrierSelectInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CarrierId" type="{http://www.metaswitch.com/cfs/billing/V1.0}CarrierIdType" minOccurs="0"/>
 *         &lt;element name="CarrierOperatorInvolved" type="{http://www.metaswitch.com/cfs/billing/V1.0}CarrierOperatorType"/>
 *         &lt;element name="SelectionMethod" type="{http://www.metaswitch.com/cfs/billing/V1.0}SelectionMethodType"/>
 *         &lt;element name="NetworkId" type="{http://www.metaswitch.com/cfs/billing/V1.0}NetworkNumberType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CarrierSelectInfoType", propOrder = {
    "carrierId",
    "carrierOperatorInvolved",
    "selectionMethod",
    "networkId"
})
public class CarrierSelectInfoType {

    @XmlElement(name = "CarrierId")
    protected Integer carrierId;
    @XmlElement(name = "CarrierOperatorInvolved", required = true)
    protected CarrierOperatorType carrierOperatorInvolved;
    @XmlElement(name = "SelectionMethod", required = true)
    protected SelectionMethodType selectionMethod;
    @XmlElement(name = "NetworkId")
    protected int networkId;

    /**
     * Gets the value of the carrierId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCarrierId() {
        return carrierId;
    }

    /**
     * Sets the value of the carrierId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCarrierId(Integer value) {
        this.carrierId = value;
    }

    /**
     * Gets the value of the carrierOperatorInvolved property.
     * 
     * @return
     *     possible object is
     *     {@link CarrierOperatorType }
     *     
     */
    public CarrierOperatorType getCarrierOperatorInvolved() {
        return carrierOperatorInvolved;
    }

    /**
     * Sets the value of the carrierOperatorInvolved property.
     * 
     * @param value
     *     allowed object is
     *     {@link CarrierOperatorType }
     *     
     */
    public void setCarrierOperatorInvolved(CarrierOperatorType value) {
        this.carrierOperatorInvolved = value;
    }

    /**
     * Gets the value of the selectionMethod property.
     * 
     * @return
     *     possible object is
     *     {@link SelectionMethodType }
     *     
     */
    public SelectionMethodType getSelectionMethod() {
        return selectionMethod;
    }

    /**
     * Sets the value of the selectionMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectionMethodType }
     *     
     */
    public void setSelectionMethod(SelectionMethodType value) {
        this.selectionMethod = value;
    }

    /**
     * Gets the value of the networkId property.
     * 
     */
    public int getNetworkId() {
        return networkId;
    }

    /**
     * Sets the value of the networkId property.
     * 
     */
    public void setNetworkId(int value) {
        this.networkId = value;
    }

}
