//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Specifies statistics about a particular class of CDRs.
 *       
 * 
 * <p>Java class for CDRsByClassType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CDRsByClassType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NormalCallCount" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *         &lt;element name="NormalCallDuration" type="{http://www.metaswitch.com/cfs/billing/V1.0}DurationType"/>
 *         &lt;element name="ForwardedCallCount" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *         &lt;element name="ForwardedCallDuration" type="{http://www.metaswitch.com/cfs/billing/V1.0}DurationType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="class" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}unsignedByte">
 *             &lt;minInclusive value="1"/>
 *             &lt;maxInclusive value="10"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CDRsByClassType", propOrder = {
    "normalCallCount",
    "normalCallDuration",
    "forwardedCallCount",
    "forwardedCallDuration"
})
public class CDRsByClassType {

    @XmlElement(name = "NormalCallCount", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger normalCallCount;
    @XmlElement(name = "NormalCallDuration", required = true)
    protected BigInteger normalCallDuration;
    @XmlElement(name = "ForwardedCallCount", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger forwardedCallCount;
    @XmlElement(name = "ForwardedCallDuration", required = true)
    protected BigInteger forwardedCallDuration;
    @XmlAttribute(name = "class", required = true)
    protected short clazz;

    /**
     * Gets the value of the normalCallCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNormalCallCount() {
        return normalCallCount;
    }

    /**
     * Sets the value of the normalCallCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNormalCallCount(BigInteger value) {
        this.normalCallCount = value;
    }

    /**
     * Gets the value of the normalCallDuration property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNormalCallDuration() {
        return normalCallDuration;
    }

    /**
     * Sets the value of the normalCallDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNormalCallDuration(BigInteger value) {
        this.normalCallDuration = value;
    }

    /**
     * Gets the value of the forwardedCallCount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getForwardedCallCount() {
        return forwardedCallCount;
    }

    /**
     * Sets the value of the forwardedCallCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setForwardedCallCount(BigInteger value) {
        this.forwardedCallCount = value;
    }

    /**
     * Gets the value of the forwardedCallDuration property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getForwardedCallDuration() {
        return forwardedCallDuration;
    }

    /**
     * Sets the value of the forwardedCallDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setForwardedCallDuration(BigInteger value) {
        this.forwardedCallDuration = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     */
    public short getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     */
    public void setClazz(short value) {
        this.clazz = value;
    }

}
