//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Contains the statistics about the classified CDRs present
 *         in the file.
 *       
 * 
 * <p>Java class for ClassifiedCDRsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClassifiedCDRsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CDRsByClass" type="{http://www.metaswitch.com/cfs/billing/V1.0}CDRsByClassType" maxOccurs="10" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClassifiedCDRsType", propOrder = {
    "cdRsByClass"
})
public class ClassifiedCDRsType {

    @XmlElement(name = "CDRsByClass")
    protected List<CDRsByClassType> cdRsByClass;

    /**
     * Gets the value of the cdRsByClass property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cdRsByClass property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCDRsByClass().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CDRsByClassType }
     * 
     * 
     */
    public List<CDRsByClassType> getCDRsByClass() {
        if (cdRsByClass == null) {
            cdRsByClass = new ArrayList<CDRsByClassType>();
        }
        return this.cdRsByClass;
    }

}
