//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Contains a list of trunks that were tried and either
 *         skipped or failed during routing of this call.
 *       
 * 
 * <p>Java class for FailedTrunkGroupsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FailedTrunkGroupsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FailedTrunkGroup" type="{http://www.metaswitch.com/cfs/billing/V1.0}FailedTrunkGroupType" maxOccurs="5"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FailedTrunkGroupsType", propOrder = {
    "failedTrunkGroup"
})
public class FailedTrunkGroupsType {

    @XmlElement(name = "FailedTrunkGroup", required = true)
    protected List<FailedTrunkGroupType> failedTrunkGroup;

    /**
     * Gets the value of the failedTrunkGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the failedTrunkGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFailedTrunkGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FailedTrunkGroupType }
     * 
     * 
     */
    public List<FailedTrunkGroupType> getFailedTrunkGroup() {
        if (failedTrunkGroup == null) {
            failedTrunkGroup = new ArrayList<FailedTrunkGroupType>();
        }
        return this.failedTrunkGroup;
    }

}
