//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * Provides supplementary information about a feature (or
 *         potentially features) that were invoked on a call. Since the actual
 *         information present depends on the exact features invoked, this type
 *         includes all possible supplementary information
 *       
 * 
 * <p>Java class for FeatureInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FeatureInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="ForwardToAddr" type="{http://www.metaswitch.com/cfs/billing/V1.0}AddressType" minOccurs="0"/>
 *         &lt;element name="RemotePartyAddr" type="{http://www.metaswitch.com/cfs/billing/V1.0}AddressType" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FeatureInfoType", propOrder = {
    "forwardToAddrOrRemotePartyAddr"
})
public class FeatureInfoType {

    @XmlElementRefs({
        @XmlElementRef(name = "RemotePartyAddr", namespace = "http://www.metaswitch.com/cfs/billing/V1.0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "ForwardToAddr", namespace = "http://www.metaswitch.com/cfs/billing/V1.0", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<AddressType>> forwardToAddrOrRemotePartyAddr;

    /**
     * Gets the value of the forwardToAddrOrRemotePartyAddr property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the forwardToAddrOrRemotePartyAddr property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getForwardToAddrOrRemotePartyAddr().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link AddressType }{@code >}
     * {@link JAXBElement }{@code <}{@link AddressType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<AddressType>> getForwardToAddrOrRemotePartyAddr() {
        if (forwardToAddrOrRemotePartyAddr == null) {
            forwardToAddrOrRemotePartyAddr = new ArrayList<JAXBElement<AddressType>>();
        }
        return this.forwardToAddrOrRemotePartyAddr;
    }

}
