//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Specifies information about the nature of the billing
 *         information contained in this file. The footer contains information
 *         that is only available once the file is complete; information that is
 *         invariant over the contents, such as the identity of the equipment
 *         generating the records, is provided in the corresponding
 *         <FileHeader>.
 *       
 * 
 * <p>Java class for FileFooterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FileFooterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LastModTime" type="{http://www.metaswitch.com/cfs/billing/V1.0}TimestampType"/>
 *         &lt;element name="NumCDRs" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *         &lt;element name="DataErroredCDRs" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *         &lt;element name="WriteErroredCDRs" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *         &lt;element name="ClassifiedCDRs" type="{http://www.metaswitch.com/cfs/billing/V1.0}ClassifiedCDRsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FileFooterType", propOrder = {
    "lastModTime",
    "numCDRs",
    "dataErroredCDRs",
    "writeErroredCDRs",
    "classifiedCDRs"
})
public class FileFooterType {

    @XmlElement(name = "LastModTime", required = true)
    protected String lastModTime;
    @XmlElement(name = "NumCDRs", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger numCDRs;
    @XmlElement(name = "DataErroredCDRs", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger dataErroredCDRs;
    @XmlElement(name = "WriteErroredCDRs", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger writeErroredCDRs;
    @XmlElement(name = "ClassifiedCDRs")
    protected ClassifiedCDRsType classifiedCDRs;

    /**
     * Gets the value of the lastModTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastModTime() {
        return lastModTime;
    }

    /**
     * Sets the value of the lastModTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastModTime(String value) {
        this.lastModTime = value;
    }

    /**
     * Gets the value of the numCDRs property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumCDRs() {
        return numCDRs;
    }

    /**
     * Sets the value of the numCDRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumCDRs(BigInteger value) {
        this.numCDRs = value;
    }

    /**
     * Gets the value of the dataErroredCDRs property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDataErroredCDRs() {
        return dataErroredCDRs;
    }

    /**
     * Sets the value of the dataErroredCDRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDataErroredCDRs(BigInteger value) {
        this.dataErroredCDRs = value;
    }

    /**
     * Gets the value of the writeErroredCDRs property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWriteErroredCDRs() {
        return writeErroredCDRs;
    }

    /**
     * Sets the value of the writeErroredCDRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWriteErroredCDRs(BigInteger value) {
        this.writeErroredCDRs = value;
    }

    /**
     * Gets the value of the classifiedCDRs property.
     * 
     * @return
     *     possible object is
     *     {@link ClassifiedCDRsType }
     *     
     */
    public ClassifiedCDRsType getClassifiedCDRs() {
        return classifiedCDRs;
    }

    /**
     * Sets the value of the classifiedCDRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassifiedCDRsType }
     *     
     */
    public void setClassifiedCDRs(ClassifiedCDRsType value) {
        this.classifiedCDRs = value;
    }

}
