//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Specifies the Intelligent Networking treatment applied to
 *         the call.
 *       
 * 
 * <p>Java class for IntelligentNetworkInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IntelligentNetworkInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ServiceLogicId" type="{http://www.metaswitch.com/cfs/billing/V1.0}ServiceLogicIdType" minOccurs="0"/>
 *         &lt;element name="ChargeAddr" type="{http://www.metaswitch.com/cfs/billing/V1.0}AddressType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="bcsm" use="required" type="{http://www.metaswitch.com/cfs/billing/V1.0}BCSMType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IntelligentNetworkInfoType", propOrder = {
    "serviceLogicId",
    "chargeAddr"
})
public class IntelligentNetworkInfoType {

    @XmlElement(name = "ServiceLogicId")
    protected Integer serviceLogicId;
    @XmlElement(name = "ChargeAddr")
    protected AddressType chargeAddr;
    @XmlAttribute(name = "bcsm", required = true)
    protected BCSMType bcsm;

    /**
     * Gets the value of the serviceLogicId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getServiceLogicId() {
        return serviceLogicId;
    }

    /**
     * Sets the value of the serviceLogicId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setServiceLogicId(Integer value) {
        this.serviceLogicId = value;
    }

    /**
     * Gets the value of the chargeAddr property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getChargeAddr() {
        return chargeAddr;
    }

    /**
     * Sets the value of the chargeAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setChargeAddr(AddressType value) {
        this.chargeAddr = value;
    }

    /**
     * Gets the value of the bcsm property.
     * 
     * @return
     *     possible object is
     *     {@link BCSMType }
     *     
     */
    public BCSMType getBcsm() {
        return bcsm;
    }

    /**
     * Sets the value of the bcsm property.
     * 
     * @param value
     *     allowed object is
     *     {@link BCSMType }
     *     
     */
    public void setBcsm(BCSMType value) {
        this.bcsm = value;
    }

}
