//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Specifies information about the interim CDRs generated
 *         in order to protect against loss of billing information for very long
 *         calls after system failure. These are termed "Long Duration
 *         Records" (LDRs). This information can be used in order to
 *         avoid double-billing for the same call and to recover billing
 *         information after a system failure that resulted in loss of final
 *         records.
 *       
 * 
 * <p>Java class for LongDurationInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LongDurationInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Status" type="{http://www.metaswitch.com/cfs/billing/V1.0}LdrStatusType"/>
 *         &lt;element name="Count" type="{http://www.metaswitch.com/cfs/billing/V1.0}CDRSeqNumType"/>
 *         &lt;element name="PreviousTime" type="{http://www.metaswitch.com/cfs/billing/V1.0}TimestampType" minOccurs="0"/>
 *         &lt;element name="CurrentTime" type="{http://www.metaswitch.com/cfs/billing/V1.0}TimestampType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LongDurationInfoType", propOrder = {
    "status",
    "count",
    "previousTime",
    "currentTime"
})
public class LongDurationInfoType {

    @XmlElement(name = "Status", required = true)
    protected LdrStatusType status;
    @XmlElement(name = "Count")
    protected int count;
    @XmlElement(name = "PreviousTime")
    protected String previousTime;
    @XmlElement(name = "CurrentTime")
    protected String currentTime;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link LdrStatusType }
     *     
     */
    public LdrStatusType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link LdrStatusType }
     *     
     */
    public void setStatus(LdrStatusType value) {
        this.status = value;
    }

    /**
     * Gets the value of the count property.
     * 
     */
    public int getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     */
    public void setCount(int value) {
        this.count = value;
    }

    /**
     * Gets the value of the previousTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreviousTime() {
        return previousTime;
    }

    /**
     * Sets the value of the previousTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreviousTime(String value) {
        this.previousTime = value;
    }

    /**
     * Gets the value of the currentTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentTime() {
        return currentTime;
    }

    /**
     * Sets the value of the currentTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentTime(String value) {
        this.currentTime = value;
    }

}
