//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Specifies the details of a party connected over a network
 *         trunk to this system.
 * 
 *         This is a concrete derivation of the abstract PartyType. Parsers may
 *         use the value of the attribute xsi:type, which will be set to
 *         "NetworkTrunkPartyType" to determine what kind of
 *         party is being described.
 *       
 * 
 * <p>Java class for NetworkTrunkPartyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NetworkTrunkPartyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.metaswitch.com/cfs/billing/V1.0}PartyType">
 *       &lt;sequence>
 *         &lt;element name="TrunkGroup" type="{http://www.metaswitch.com/cfs/billing/V1.0}TrunkGroupType"/>
 *         &lt;element name="CallingPartyAddr" type="{http://www.metaswitch.com/cfs/billing/V1.0}AddressType" minOccurs="0"/>
 *         &lt;element name="UserAgent" type="{http://www.metaswitch.com/cfs/billing/V1.0}UserAgentType" minOccurs="0"/>
 *         &lt;element name="SIPCallId" type="{http://www.metaswitch.com/cfs/billing/V1.0}SIPCallIdType" minOccurs="0"/>
 *         &lt;element name="SignalingType" type="{http://www.metaswitch.com/cfs/billing/V1.0}SignalingTypeType" minOccurs="0"/>
 *         &lt;element name="SourceAddresses" type="{http://www.metaswitch.com/cfs/billing/V1.0}AddressesType" minOccurs="0"/>
 *         &lt;element name="DestAddresses" type="{http://www.metaswitch.com/cfs/billing/V1.0}AddressesType" minOccurs="0"/>
 *         &lt;element name="RequestURI" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="From" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="To" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Contact" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Via" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PAssertedIdentity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RemotePartyId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PAccessNetworkInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Reason" type="{http://www.metaswitch.com/cfs/billing/V1.0}TrunkFailReasonType" maxOccurs="2" minOccurs="0"/>
 *         &lt;element name="Gateway" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VQM" type="{http://www.metaswitch.com/cfs/billing/V1.0}VQMType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="privacy" type="{http://www.metaswitch.com/cfs/billing/V1.0}PrivacyType" />
 *       &lt;attribute name="cpc" type="{http://www.metaswitch.com/cfs/billing/V1.0}CallingPartyCategoryType" />
 *       &lt;attribute name="ani-ii" type="{http://www.metaswitch.com/cfs/billing/V1.0}ANI-IIType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NetworkTrunkPartyType")
public class NetworkTrunkPartyType
    extends PartyType
{


}
