//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Specifies the number-portability treatment applied to a
 *         call. This information only applies to North American LRN lookups.
 *         The treatment of other LNP schemes, such as All Call Query, can be
 *         deduced from the regular routing information in the CDR.
 *       
 * 
 * <p>Java class for NPInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NPInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="NPRoutingNumber" type="{http://www.metaswitch.com/cfs/billing/V1.0}NPRoutingNumberType"/>
 *         &lt;element name="NPSource" type="{http://www.metaswitch.com/cfs/billing/V1.0}NpSourceType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="partyidentifier" use="required" type="{http://www.metaswitch.com/cfs/billing/V1.0}NpPartyType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NPInfoType", propOrder = {
    "npRoutingNumber",
    "npSource"
})
public class NPInfoType {

    @XmlElement(name = "NPRoutingNumber", required = true)
    protected NPRoutingNumberType npRoutingNumber;
    @XmlElement(name = "NPSource", required = true)
    protected NpSourceType npSource;
    @XmlAttribute(name = "partyidentifier", required = true)
    protected NpPartyType partyidentifier;

    /**
     * Gets the value of the npRoutingNumber property.
     * 
     * @return
     *     possible object is
     *     {@link NPRoutingNumberType }
     *     
     */
    public NPRoutingNumberType getNPRoutingNumber() {
        return npRoutingNumber;
    }

    /**
     * Sets the value of the npRoutingNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link NPRoutingNumberType }
     *     
     */
    public void setNPRoutingNumber(NPRoutingNumberType value) {
        this.npRoutingNumber = value;
    }

    /**
     * Gets the value of the npSource property.
     * 
     * @return
     *     possible object is
     *     {@link NpSourceType }
     *     
     */
    public NpSourceType getNPSource() {
        return npSource;
    }

    /**
     * Sets the value of the npSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link NpSourceType }
     *     
     */
    public void setNPSource(NpSourceType value) {
        this.npSource = value;
    }

    /**
     * Gets the value of the partyidentifier property.
     * 
     * @return
     *     possible object is
     *     {@link NpPartyType }
     *     
     */
    public NpPartyType getPartyidentifier() {
        return partyidentifier;
    }

    /**
     * Sets the value of the partyidentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link NpPartyType }
     *     
     */
    public void setPartyidentifier(NpPartyType value) {
        this.partyidentifier = value;
    }

}
