//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NpPartyType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NpPartyType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="orig"/>
 *     &lt;enumeration value="term"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "NpPartyType")
@XmlEnum
public enum NpPartyType {


    /**
     * The NP information relates to the originating party.
     *           
     * 
     */
    @XmlEnumValue("orig")
    ORIG("orig"),

    /**
     * The NP information relates to the terminating party.
     *           
     * 
     */
    @XmlEnumValue("term")
    TERM("term");
    private final String value;

    NpPartyType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NpPartyType fromValue(String v) {
        for (NpPartyType c: NpPartyType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
