//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the javalearning.xml.cfs package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _File_QNAME = new QName("http://www.metaswitch.com/cfs/billing/V1.0", "File");
    private final static QName _FeatureInfoTypeRemotePartyAddr_QNAME = new QName("http://www.metaswitch.com/cfs/billing/V1.0", "RemotePartyAddr");
    private final static QName _FeatureInfoTypeForwardToAddr_QNAME = new QName("http://www.metaswitch.com/cfs/billing/V1.0", "ForwardToAddr");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: javalearning.xml.cfs
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FileType }
     * 
     */
    public FileType createFileType() {
        return new FileType();
    }

    /**
     * Create an instance of {@link FileFooterType }
     * 
     */
    public FileFooterType createFileFooterType() {
        return new FileFooterType();
    }

    /**
     * Create an instance of {@link NPRoutingNumberType }
     * 
     */
    public NPRoutingNumberType createNPRoutingNumberType() {
        return new NPRoutingNumberType();
    }

    /**
     * Create an instance of {@link SignalingTypeType }
     * 
     */
    public SignalingTypeType createSignalingTypeType() {
        return new SignalingTypeType();
    }

    /**
     * Create an instance of {@link CallForwardInfoType }
     * 
     */
    public CallForwardInfoType createCallForwardInfoType() {
        return new CallForwardInfoType();
    }

    /**
     * Create an instance of {@link CodecsType }
     * 
     */
    public CodecsType createCodecsType() {
        return new CodecsType();
    }

    /**
     * Create an instance of {@link IntelligentNetworkInfoType }
     * 
     */
    public IntelligentNetworkInfoType createIntelligentNetworkInfoType() {
        return new IntelligentNetworkInfoType();
    }

    /**
     * Create an instance of {@link UserServiceType }
     * 
     */
    public UserServiceType createUserServiceType() {
        return new UserServiceType();
    }

    /**
     * Create an instance of {@link VQMOctetStatsType }
     * 
     */
    public VQMOctetStatsType createVQMOctetStatsType() {
        return new VQMOctetStatsType();
    }

    /**
     * Create an instance of {@link BusinessLinePartyType }
     * 
     */
    public BusinessLinePartyType createBusinessLinePartyType() {
        return new BusinessLinePartyType();
    }

    /**
     * Create an instance of {@link SignalingInfoType }
     * 
     */
    public SignalingInfoType createSignalingInfoType() {
        return new SignalingInfoType();
    }

    /**
     * Create an instance of {@link UUIServicesType }
     * 
     */
    public UUIServicesType createUUIServicesType() {
        return new UUIServicesType();
    }

    /**
     * Create an instance of {@link PChargingFunctionAddressesType }
     * 
     */
    public PChargingFunctionAddressesType createPChargingFunctionAddressesType() {
        return new PChargingFunctionAddressesType();
    }

    /**
     * Create an instance of {@link CallType }
     * 
     */
    public CallType createCallType() {
        return new CallType();
    }

    /**
     * Create an instance of {@link FailedTrunkGroupType }
     * 
     */
    public FailedTrunkGroupType createFailedTrunkGroupType() {
        return new FailedTrunkGroupType();
    }

    /**
     * Create an instance of {@link AppServerPartyType }
     * 
     */
    public AppServerPartyType createAppServerPartyType() {
        return new AppServerPartyType();
    }

    /**
     * Create an instance of {@link NetworkTrunkPartyType }
     * 
     */
    public NetworkTrunkPartyType createNetworkTrunkPartyType() {
        return new NetworkTrunkPartyType();
    }

    /**
     * Create an instance of {@link TrunkFailReasonType }
     * 
     */
    public TrunkFailReasonType createTrunkFailReasonType() {
        return new TrunkFailReasonType();
    }

    /**
     * Create an instance of {@link MLHGPilotPartyType }
     * 
     */
    public MLHGPilotPartyType createMLHGPilotPartyType() {
        return new MLHGPilotPartyType();
    }

    /**
     * Create an instance of {@link CustomerCodeType }
     * 
     */
    public CustomerCodeType createCustomerCodeType() {
        return new CustomerCodeType();
    }

    /**
     * Create an instance of {@link RoutingInfoType }
     * 
     */
    public RoutingInfoType createRoutingInfoType() {
        return new RoutingInfoType();
    }

    /**
     * Create an instance of {@link PBXPartyType }
     * 
     */
    public PBXPartyType createPBXPartyType() {
        return new PBXPartyType();
    }

    /**
     * Create an instance of {@link IndividualLinePartyType }
     * 
     */
    public IndividualLinePartyType createIndividualLinePartyType() {
        return new IndividualLinePartyType();
    }

    /**
     * Create an instance of {@link FileHeaderType }
     * 
     */
    public FileHeaderType createFileHeaderType() {
        return new FileHeaderType();
    }

    /**
     * Create an instance of {@link FeatureInfoType }
     * 
     */
    public FeatureInfoType createFeatureInfoType() {
        return new FeatureInfoType();
    }

    /**
     * Create an instance of {@link UDAType }
     * 
     */
    public UDAType createUDAType() {
        return new UDAType();
    }

    /**
     * Create an instance of {@link VQMDelayStatsType }
     * 
     */
    public VQMDelayStatsType createVQMDelayStatsType() {
        return new VQMDelayStatsType();
    }

    /**
     * Create an instance of {@link Announcement }
     * 
     */
    public Announcement createAnnouncement() {
        return new Announcement();
    }

    /**
     * Create an instance of {@link VQMPacketStatsType }
     * 
     */
    public VQMPacketStatsType createVQMPacketStatsType() {
        return new VQMPacketStatsType();
    }

    /**
     * Create an instance of {@link NoPartyPartyType }
     * 
     */
    public NoPartyPartyType createNoPartyPartyType() {
        return new NoPartyPartyType();
    }

    /**
     * Create an instance of {@link CDRsByClassType }
     * 
     */
    public CDRsByClassType createCDRsByClassType() {
        return new CDRsByClassType();
    }

    /**
     * Create an instance of {@link VQMType }
     * 
     */
    public VQMType createVQMType() {
        return new VQMType();
    }

    /**
     * Create an instance of {@link CalledPartyNumCat }
     * 
     */
    public CalledPartyNumCat createCalledPartyNumCat() {
        return new CalledPartyNumCat();
    }

    /**
     * Create an instance of {@link SatelliteIndicatorType }
     * 
     */
    public SatelliteIndicatorType createSatelliteIndicatorType() {
        return new SatelliteIndicatorType();
    }

    /**
     * Create an instance of {@link CallReferenceType }
     * 
     */
    public CallReferenceType createCallReferenceType() {
        return new CallReferenceType();
    }

    /**
     * Create an instance of {@link FeaturesType }
     * 
     */
    public FeaturesType createFeaturesType() {
        return new FeaturesType();
    }

    /**
     * Create an instance of {@link AddressesType }
     * 
     */
    public AddressesType createAddressesType() {
        return new AddressesType();
    }

    /**
     * Create an instance of {@link VQMCallQualityStatsType }
     * 
     */
    public VQMCallQualityStatsType createVQMCallQualityStatsType() {
        return new VQMCallQualityStatsType();
    }

    /**
     * Create an instance of {@link ReleaseReasonType }
     * 
     */
    public ReleaseReasonType createReleaseReasonType() {
        return new ReleaseReasonType();
    }

    /**
     * Create an instance of {@link UDAsType }
     * 
     */
    public UDAsType createUDAsType() {
        return new UDAsType();
    }

    /**
     * Create an instance of {@link ClassifiedCDRsType }
     * 
     */
    public ClassifiedCDRsType createClassifiedCDRsType() {
        return new ClassifiedCDRsType();
    }

    /**
     * Create an instance of {@link TrunkGroupType }
     * 
     */
    public TrunkGroupType createTrunkGroupType() {
        return new TrunkGroupType();
    }

    /**
     * Create an instance of {@link CarrierSelectInfoType }
     * 
     */
    public CarrierSelectInfoType createCarrierSelectInfoType() {
        return new CarrierSelectInfoType();
    }

    /**
     * Create an instance of {@link EventType }
     * 
     */
    public EventType createEventType() {
        return new EventType();
    }

    /**
     * Create an instance of {@link VQMTermStatsType }
     * 
     */
    public VQMTermStatsType createVQMTermStatsType() {
        return new VQMTermStatsType();
    }

    /**
     * Create an instance of {@link UUIServiceType }
     * 
     */
    public UUIServiceType createUUIServiceType() {
        return new UUIServiceType();
    }

    /**
     * Create an instance of {@link CdrsType }
     * 
     */
    public CdrsType createCdrsType() {
        return new CdrsType();
    }

    /**
     * Create an instance of {@link MADNPartyType }
     * 
     */
    public MADNPartyType createMADNPartyType() {
        return new MADNPartyType();
    }

    /**
     * Create an instance of {@link EchoControlInfoType }
     * 
     */
    public EchoControlInfoType createEchoControlInfoType() {
        return new EchoControlInfoType();
    }

    /**
     * Create an instance of {@link PeerType }
     * 
     */
    public PeerType createPeerType() {
        return new PeerType();
    }

    /**
     * Create an instance of {@link FailedTrunkGroupsType }
     * 
     */
    public FailedTrunkGroupsType createFailedTrunkGroupsType() {
        return new FailedTrunkGroupsType();
    }

    /**
     * Create an instance of {@link AnnouncementType }
     * 
     */
    public AnnouncementType createAnnouncementType() {
        return new AnnouncementType();
    }

    /**
     * Create an instance of {@link PChargingVectorType }
     * 
     */
    public PChargingVectorType createPChargingVectorType() {
        return new PChargingVectorType();
    }

    /**
     * Create an instance of {@link NPInfoType }
     * 
     */
    public NPInfoType createNPInfoType() {
        return new NPInfoType();
    }

    /**
     * Create an instance of {@link LongDurationInfoType }
     * 
     */
    public LongDurationInfoType createLongDurationInfoType() {
        return new LongDurationInfoType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link InformationTransferCapabilityType }
     * 
     */
    public InformationTransferCapabilityType createInformationTransferCapabilityType() {
        return new InformationTransferCapabilityType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FileType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.metaswitch.com/cfs/billing/V1.0", name = "File")
    public JAXBElement<FileType> createFile(FileType value) {
        return new JAXBElement<FileType>(_File_QNAME, FileType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.metaswitch.com/cfs/billing/V1.0", name = "RemotePartyAddr", scope = FeatureInfoType.class)
    public JAXBElement<AddressType> createFeatureInfoTypeRemotePartyAddr(AddressType value) {
        return new JAXBElement<AddressType>(_FeatureInfoTypeRemotePartyAddr_QNAME, AddressType.class, FeatureInfoType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.metaswitch.com/cfs/billing/V1.0", name = "ForwardToAddr", scope = FeatureInfoType.class)
    public JAXBElement<AddressType> createFeatureInfoTypeForwardToAddr(AddressType value) {
        return new JAXBElement<AddressType>(_FeatureInfoTypeForwardToAddr_QNAME, AddressType.class, FeatureInfoType.class, value);
    }

}
