//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.metaswitch.com/cfs/billing/V1.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package javalearning.xml.cfs;
