//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Specifies parties involved in calls as calling, called or
 *         served users.
 * 
 *         This is an abstract base type that must be derived (generally by
 *         restriction) to produce a concrete type, such as the
 *         "IndividualLinePartyType".
 * 
 *         The elements of this type are generally shown as optional (minOccurs=0,
 *         maxOccurs=1) but this is normally constrained in the derived types to
 *         be either mandatory or absent, as appropriate.
 * 
 *         In order to ensure that the correct interpretation of the contents can
 *         be made, the element will always include an xsi:type attribute that
 *         enables parsers to switch their behaviour according to the expected
 *         content model.
 * 
 *         To ensure that documentation is in one place, the elements are
 *         documented on this base type, rather than the derived types.
 *         
 * 
 * <p>Java class for PartyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PartyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TrunkGroup" type="{http://www.metaswitch.com/cfs/billing/V1.0}TrunkGroupType" minOccurs="0"/>
 *         &lt;element name="SubscriberAddr" type="{http://www.metaswitch.com/cfs/billing/V1.0}AddressType" minOccurs="0"/>
 *         &lt;element name="CallingPartyAddr" type="{http://www.metaswitch.com/cfs/billing/V1.0}AddressType" minOccurs="0"/>
 *         &lt;element name="ChargeAddr" type="{http://www.metaswitch.com/cfs/billing/V1.0}AddressType" minOccurs="0"/>
 *         &lt;element name="BusinessGroupName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Extension" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AppServerAddr" type="{http://www.metaswitch.com/cfs/billing/V1.0}AddressType" minOccurs="0"/>
 *         &lt;element name="ServedParty" type="{http://www.metaswitch.com/cfs/billing/V1.0}PartyType" minOccurs="0"/>
 *         &lt;element name="UserAgent" type="{http://www.metaswitch.com/cfs/billing/V1.0}UserAgentType" minOccurs="0"/>
 *         &lt;element name="SIPCallId" type="{http://www.metaswitch.com/cfs/billing/V1.0}SIPCallIdType" minOccurs="0"/>
 *         &lt;element name="SignalingType" type="{http://www.metaswitch.com/cfs/billing/V1.0}SignalingTypeType" minOccurs="0"/>
 *         &lt;element name="SourceAddresses" type="{http://www.metaswitch.com/cfs/billing/V1.0}AddressesType" minOccurs="0"/>
 *         &lt;element name="DestAddresses" type="{http://www.metaswitch.com/cfs/billing/V1.0}AddressesType" minOccurs="0"/>
 *         &lt;element name="RequestURI" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="From" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="To" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Contact" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Via" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PAssertedIdentity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RemotePartyId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PAccessNetworkInfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="OrigPointCode" type="{http://www.metaswitch.com/cfs/billing/V1.0}PointCodeDecimalType" minOccurs="0"/>
 *         &lt;element name="DestPointCode" type="{http://www.metaswitch.com/cfs/billing/V1.0}PointCodeDecimalType" minOccurs="0"/>
 *         &lt;element name="Reason" type="{http://www.metaswitch.com/cfs/billing/V1.0}TrunkFailReasonType" maxOccurs="2" minOccurs="0"/>
 *         &lt;element name="Gateway" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="VQM" type="{http://www.metaswitch.com/cfs/billing/V1.0}VQMType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="subscribergroup" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="privacy" type="{http://www.metaswitch.com/cfs/billing/V1.0}PrivacyType" />
 *       &lt;attribute name="billingtype" type="{http://www.metaswitch.com/cfs/billing/V1.0}BillingTypeType" />
 *       &lt;attribute name="cpc" type="{http://www.metaswitch.com/cfs/billing/V1.0}CallingPartyCategoryType" />
 *       &lt;attribute name="ani-ii" type="{http://www.metaswitch.com/cfs/billing/V1.0}ANI-IIType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PartyType", propOrder = {
    "trunkGroup",
    "subscriberAddr",
    "callingPartyAddr",
    "chargeAddr",
    "businessGroupName",
    "extension",
    "appServerAddr",
    "servedParty",
    "userAgent",
    "sipCallId",
    "signalingType",
    "sourceAddresses",
    "destAddresses",
    "requestURI",
    "from",
    "to",
    "contact",
    "via",
    "pAssertedIdentity",
    "remotePartyId",
    "pAccessNetworkInfo",
    "origPointCode",
    "destPointCode",
    "reason",
    "gateway",
    "vqm"
})
@XmlSeeAlso({
    BusinessLinePartyType.class,
    AppServerPartyType.class,
    NetworkTrunkPartyType.class,
    MLHGPilotPartyType.class,
    PBXPartyType.class,
    IndividualLinePartyType.class,
    NoPartyPartyType.class,
    MADNPartyType.class
})
public abstract class PartyType {

    @XmlElement(name = "TrunkGroup")
    protected TrunkGroupType trunkGroup;
    @XmlElement(name = "SubscriberAddr")
    protected AddressType subscriberAddr;
    @XmlElement(name = "CallingPartyAddr")
    protected AddressType callingPartyAddr;
    @XmlElement(name = "ChargeAddr")
    protected AddressType chargeAddr;
    @XmlElement(name = "BusinessGroupName")
    protected String businessGroupName;
    @XmlElement(name = "Extension")
    protected String extension;
    @XmlElement(name = "AppServerAddr")
    protected AddressType appServerAddr;
    @XmlElement(name = "ServedParty")
    protected PartyType servedParty;
    @XmlElement(name = "UserAgent")
    protected String userAgent;
    @XmlElement(name = "SIPCallId")
    protected String sipCallId;
    @XmlElement(name = "SignalingType")
    protected SignalingTypeType signalingType;
    @XmlElement(name = "SourceAddresses")
    protected AddressesType sourceAddresses;
    @XmlElement(name = "DestAddresses")
    protected AddressesType destAddresses;
    @XmlElement(name = "RequestURI")
    protected String requestURI;
    @XmlElement(name = "From")
    protected String from;
    @XmlElement(name = "To")
    protected String to;
    @XmlElement(name = "Contact")
    protected String contact;
    @XmlElement(name = "Via")
    protected String via;
    @XmlElement(name = "PAssertedIdentity")
    protected String pAssertedIdentity;
    @XmlElement(name = "RemotePartyId")
    protected String remotePartyId;
    @XmlElement(name = "PAccessNetworkInfo")
    protected String pAccessNetworkInfo;
    @XmlElement(name = "OrigPointCode")
    protected String origPointCode;
    @XmlElement(name = "DestPointCode")
    protected String destPointCode;
    @XmlElement(name = "Reason")
    protected List<TrunkFailReasonType> reason;
    @XmlElement(name = "Gateway")
    protected String gateway;
    @XmlElement(name = "VQM")
    protected VQMType vqm;
    @XmlAttribute(name = "subscribergroup")
    protected String subscribergroup;
    @XmlAttribute(name = "privacy")
    protected PrivacyType privacy;
    @XmlAttribute(name = "billingtype")
    protected BillingTypeType billingtype;
    @XmlAttribute(name = "cpc")
    protected CallingPartyCategoryType cpc;
    @XmlAttribute(name = "ani-ii")
    protected String aniIi;

    /**
     * Gets the value of the trunkGroup property.
     * 
     * @return
     *     possible object is
     *     {@link TrunkGroupType }
     *     
     */
    public TrunkGroupType getTrunkGroup() {
        return trunkGroup;
    }

    /**
     * Sets the value of the trunkGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrunkGroupType }
     *     
     */
    public void setTrunkGroup(TrunkGroupType value) {
        this.trunkGroup = value;
    }

    /**
     * Gets the value of the subscriberAddr property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getSubscriberAddr() {
        return subscriberAddr;
    }

    /**
     * Sets the value of the subscriberAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setSubscriberAddr(AddressType value) {
        this.subscriberAddr = value;
    }

    /**
     * Gets the value of the callingPartyAddr property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getCallingPartyAddr() {
        return callingPartyAddr;
    }

    /**
     * Sets the value of the callingPartyAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setCallingPartyAddr(AddressType value) {
        this.callingPartyAddr = value;
    }

    /**
     * Gets the value of the chargeAddr property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getChargeAddr() {
        return chargeAddr;
    }

    /**
     * Sets the value of the chargeAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setChargeAddr(AddressType value) {
        this.chargeAddr = value;
    }

    /**
     * Gets the value of the businessGroupName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessGroupName() {
        return businessGroupName;
    }

    /**
     * Sets the value of the businessGroupName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessGroupName(String value) {
        this.businessGroupName = value;
    }

    /**
     * Gets the value of the extension property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtension() {
        return extension;
    }

    /**
     * Sets the value of the extension property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtension(String value) {
        this.extension = value;
    }

    /**
     * Gets the value of the appServerAddr property.
     * 
     * @return
     *     possible object is
     *     {@link AddressType }
     *     
     */
    public AddressType getAppServerAddr() {
        return appServerAddr;
    }

    /**
     * Sets the value of the appServerAddr property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressType }
     *     
     */
    public void setAppServerAddr(AddressType value) {
        this.appServerAddr = value;
    }

    /**
     * Gets the value of the servedParty property.
     * 
     * @return
     *     possible object is
     *     {@link PartyType }
     *     
     */
    public PartyType getServedParty() {
        return servedParty;
    }

    /**
     * Sets the value of the servedParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link PartyType }
     *     
     */
    public void setServedParty(PartyType value) {
        this.servedParty = value;
    }

    /**
     * Gets the value of the userAgent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * Sets the value of the userAgent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserAgent(String value) {
        this.userAgent = value;
    }

    /**
     * Gets the value of the sipCallId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSIPCallId() {
        return sipCallId;
    }

    /**
     * Sets the value of the sipCallId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSIPCallId(String value) {
        this.sipCallId = value;
    }

    /**
     * Gets the value of the signalingType property.
     * 
     * @return
     *     possible object is
     *     {@link SignalingTypeType }
     *     
     */
    public SignalingTypeType getSignalingType() {
        return signalingType;
    }

    /**
     * Sets the value of the signalingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignalingTypeType }
     *     
     */
    public void setSignalingType(SignalingTypeType value) {
        this.signalingType = value;
    }

    /**
     * Gets the value of the sourceAddresses property.
     * 
     * @return
     *     possible object is
     *     {@link AddressesType }
     *     
     */
    public AddressesType getSourceAddresses() {
        return sourceAddresses;
    }

    /**
     * Sets the value of the sourceAddresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressesType }
     *     
     */
    public void setSourceAddresses(AddressesType value) {
        this.sourceAddresses = value;
    }

    /**
     * Gets the value of the destAddresses property.
     * 
     * @return
     *     possible object is
     *     {@link AddressesType }
     *     
     */
    public AddressesType getDestAddresses() {
        return destAddresses;
    }

    /**
     * Sets the value of the destAddresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddressesType }
     *     
     */
    public void setDestAddresses(AddressesType value) {
        this.destAddresses = value;
    }

    /**
     * Gets the value of the requestURI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestURI() {
        return requestURI;
    }

    /**
     * Sets the value of the requestURI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestURI(String value) {
        this.requestURI = value;
    }

    /**
     * Gets the value of the from property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrom() {
        return from;
    }

    /**
     * Sets the value of the from property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrom(String value) {
        this.from = value;
    }

    /**
     * Gets the value of the to property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTo() {
        return to;
    }

    /**
     * Sets the value of the to property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTo(String value) {
        this.to = value;
    }

    /**
     * Gets the value of the contact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContact() {
        return contact;
    }

    /**
     * Sets the value of the contact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContact(String value) {
        this.contact = value;
    }

    /**
     * Gets the value of the via property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVia() {
        return via;
    }

    /**
     * Sets the value of the via property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVia(String value) {
        this.via = value;
    }

    /**
     * Gets the value of the pAssertedIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAssertedIdentity() {
        return pAssertedIdentity;
    }

    /**
     * Sets the value of the pAssertedIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAssertedIdentity(String value) {
        this.pAssertedIdentity = value;
    }

    /**
     * Gets the value of the remotePartyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemotePartyId() {
        return remotePartyId;
    }

    /**
     * Sets the value of the remotePartyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemotePartyId(String value) {
        this.remotePartyId = value;
    }

    /**
     * Gets the value of the pAccessNetworkInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPAccessNetworkInfo() {
        return pAccessNetworkInfo;
    }

    /**
     * Sets the value of the pAccessNetworkInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPAccessNetworkInfo(String value) {
        this.pAccessNetworkInfo = value;
    }

    /**
     * Gets the value of the origPointCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigPointCode() {
        return origPointCode;
    }

    /**
     * Sets the value of the origPointCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigPointCode(String value) {
        this.origPointCode = value;
    }

    /**
     * Gets the value of the destPointCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestPointCode() {
        return destPointCode;
    }

    /**
     * Sets the value of the destPointCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestPointCode(String value) {
        this.destPointCode = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reason property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReason().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TrunkFailReasonType }
     * 
     * 
     */
    public List<TrunkFailReasonType> getReason() {
        if (reason == null) {
            reason = new ArrayList<TrunkFailReasonType>();
        }
        return this.reason;
    }

    /**
     * Gets the value of the gateway property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGateway() {
        return gateway;
    }

    /**
     * Sets the value of the gateway property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGateway(String value) {
        this.gateway = value;
    }

    /**
     * Gets the value of the vqm property.
     * 
     * @return
     *     possible object is
     *     {@link VQMType }
     *     
     */
    public VQMType getVQM() {
        return vqm;
    }

    /**
     * Sets the value of the vqm property.
     * 
     * @param value
     *     allowed object is
     *     {@link VQMType }
     *     
     */
    public void setVQM(VQMType value) {
        this.vqm = value;
    }

    /**
     * Gets the value of the subscribergroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubscribergroup() {
        return subscribergroup;
    }

    /**
     * Sets the value of the subscribergroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubscribergroup(String value) {
        this.subscribergroup = value;
    }

    /**
     * Gets the value of the privacy property.
     * 
     * @return
     *     possible object is
     *     {@link PrivacyType }
     *     
     */
    public PrivacyType getPrivacy() {
        return privacy;
    }

    /**
     * Sets the value of the privacy property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrivacyType }
     *     
     */
    public void setPrivacy(PrivacyType value) {
        this.privacy = value;
    }

    /**
     * Gets the value of the billingtype property.
     * 
     * @return
     *     possible object is
     *     {@link BillingTypeType }
     *     
     */
    public BillingTypeType getBillingtype() {
        return billingtype;
    }

    /**
     * Sets the value of the billingtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link BillingTypeType }
     *     
     */
    public void setBillingtype(BillingTypeType value) {
        this.billingtype = value;
    }

    /**
     * Gets the value of the cpc property.
     * 
     * @return
     *     possible object is
     *     {@link CallingPartyCategoryType }
     *     
     */
    public CallingPartyCategoryType getCpc() {
        return cpc;
    }

    /**
     * Sets the value of the cpc property.
     * 
     * @param value
     *     allowed object is
     *     {@link CallingPartyCategoryType }
     *     
     */
    public void setCpc(CallingPartyCategoryType value) {
        this.cpc = value;
    }

    /**
     * Gets the value of the aniIi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAniIi() {
        return aniIi;
    }

    /**
     * Sets the value of the aniIi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAniIi(String value) {
        this.aniIi = value;
    }

}
