//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines the information provided by the P-Charging-Vector
 *         header in a SIP INVITE.
 * 
 *         Introduced: Version 1.0, Compatibility Level 8.
 *       
 * 
 * <p>Java class for PChargingVectorType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PChargingVectorType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="icidvalue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="icidgeneratedat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="origioi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="termioi" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PChargingVectorType", propOrder = {
    "icidvalue",
    "icidgeneratedat",
    "origioi",
    "termioi"
})
public class PChargingVectorType {

    protected String icidvalue;
    protected String icidgeneratedat;
    protected String origioi;
    protected String termioi;

    /**
     * Gets the value of the icidvalue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIcidvalue() {
        return icidvalue;
    }

    /**
     * Sets the value of the icidvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIcidvalue(String value) {
        this.icidvalue = value;
    }

    /**
     * Gets the value of the icidgeneratedat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIcidgeneratedat() {
        return icidgeneratedat;
    }

    /**
     * Sets the value of the icidgeneratedat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIcidgeneratedat(String value) {
        this.icidgeneratedat = value;
    }

    /**
     * Gets the value of the origioi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrigioi() {
        return origioi;
    }

    /**
     * Sets the value of the origioi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrigioi(String value) {
        this.origioi = value;
    }

    /**
     * Gets the value of the termioi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermioi() {
        return termioi;
    }

    /**
     * Sets the value of the termioi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermioi(String value) {
        this.termioi = value;
    }

}
