//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines the contents of the P-Charging-Function-Addresses
 *         in SIP messages.
 * 
 *         Introduced: Version 1.0, Compatibility Level 8.
 *       
 * 
 * <p>Java class for PChargingFunctionAddressesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PChargingFunctionAddressesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CCFAddresses" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ECFAddresses" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PChargingFunctionAddressesType", propOrder = {
    "ccfAddresses",
    "ecfAddresses"
})
public class PChargingFunctionAddressesType {

    @XmlElement(name = "CCFAddresses")
    protected String ccfAddresses;
    @XmlElement(name = "ECFAddresses")
    protected String ecfAddresses;

    /**
     * Gets the value of the ccfAddresses property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCCFAddresses() {
        return ccfAddresses;
    }

    /**
     * Sets the value of the ccfAddresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCCFAddresses(String value) {
        this.ccfAddresses = value;
    }

    /**
     * Gets the value of the ecfAddresses property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECFAddresses() {
        return ecfAddresses;
    }

    /**
     * Sets the value of the ecfAddresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECFAddresses(String value) {
        this.ecfAddresses = value;
    }

}
