//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PeerTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PeerTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="pc"/>
 *     &lt;enumeration value="ipv4"/>
 *     &lt;enumeration value="ipv6"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PeerTypeType")
@XmlEnum
public enum PeerTypeType {


    /**
     * The address space is MTP3 point-codes.
     *           
     * 
     */
    @XmlEnumValue("pc")
    PC("pc"),

    /**
     * The address space is IPv4.
     *           
     * 
     */
    @XmlEnumValue("ipv4")
    IPV_4("ipv4"),

    /**
     * The address space is IPv6.
     *           
     * 
     */
    @XmlEnumValue("ipv6")
    IPV_6("ipv6");
    private final String value;

    PeerTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PeerTypeType fromValue(String v) {
        for (PeerTypeType c: PeerTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
