//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Specifies the signaling peer's address in the appropriate
 *         address space for the different signaling types and the appropriate
 *         role (originating or terminating).
 * 
 *         Introduced: Version 1.0, Compatibility Level 2.
 *       
 * 
 * <p>Java class for PeerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PeerType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.metaswitch.com/cfs/billing/V1.0>PeerAddressType">
 *       &lt;attribute name="role" use="required" type="{http://www.metaswitch.com/cfs/billing/V1.0}PeerRoleType" />
 *       &lt;attribute name="type" use="required" type="{http://www.metaswitch.com/cfs/billing/V1.0}PeerTypeType" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PeerType", propOrder = {
    "value"
})
public class PeerType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "role", required = true)
    protected PeerRoleType role;
    @XmlAttribute(name = "type", required = true)
    protected PeerTypeType type;

    /**
     * Specifies the signaling peer's address in the appropriate
     *         address space for the different signaling types.
     * 
     *         Introduced: Version 1.0, Compatibility Level 2.
     *       
     * 
     * Union of address types.
     *           
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link PeerRoleType }
     *     
     */
    public PeerRoleType getRole() {
        return role;
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeerRoleType }
     *     
     */
    public void setRole(PeerRoleType value) {
        this.role = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link PeerTypeType }
     *     
     */
    public PeerTypeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeerTypeType }
     *     
     */
    public void setType(PeerTypeType value) {
        this.type = value;
    }

}
