//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReleaseReasonTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ReleaseReasonTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="q850"/>
 *     &lt;enumeration value="internal"/>
 *     &lt;enumeration value="national"/>
 *     &lt;enumeration value="network spec"/>
 *     &lt;enumeration value="sip"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ReleaseReasonTypeType")
@XmlEnum
public enum ReleaseReasonTypeType {


    /**
     * The release cause is a standard ITU-T Q.850 value.
     *             See http://www.itu.int/rec/T-REC-Q.850/en.
     *           
     * 
     */
    @XmlEnumValue("q850")
    Q_850("q850"),

    /**
     * The release cause is an internal release cause value.
     *           
     * 
     */
    @XmlEnumValue("internal")
    INTERNAL("internal"),

    /**
     * The release cause is a nationally specified value.
     *           
     * 
     */
    @XmlEnumValue("national")
    NATIONAL("national"),

    /**
     * The release cause is a network-specific value.
     *           
     * 
     */
    @XmlEnumValue("network spec")
    NETWORK_SPEC("network spec"),

    /**
     * The release cause is a network-specific value.
     * 
     *             Introduced: Version 1.0, Compatibility Level 2.
     *           
     * 
     */
    @XmlEnumValue("sip")
    SIP("sip");
    private final String value;

    ReleaseReasonTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ReleaseReasonTypeType fromValue(String v) {
        for (ReleaseReasonTypeType c: ReleaseReasonTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
