//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Specifies why a call was released. The namespace of the
 *         reason code may depend on the underlying signaling technology so the
 *         type attribute should be used to decide how to interpret the value.
 *       
 * 
 * <p>Java class for ReleaseReasonType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReleaseReasonType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.metaswitch.com/cfs/billing/V1.0>ReleaseReasonCodesType">
 *       &lt;attribute name="type" use="required" type="{http://www.metaswitch.com/cfs/billing/V1.0}ReleaseReasonTypeType" />
 *       &lt;attribute name="loc" type="{http://www.metaswitch.com/cfs/billing/V1.0}ReleaseLocationType" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReleaseReasonType", propOrder = {
    "value"
})
public class ReleaseReasonType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "type", required = true)
    protected ReleaseReasonTypeType type;
    @XmlAttribute(name = "loc")
    protected ReleaseLocationType loc;

    /**
     * Specifies the reason the call was released. May depend
     *         on the underlying signalling technology.
     *       
     * 
     * Union of Q.850 release causes and SIP response codes
     *           are possible.
     *           
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ReleaseReasonTypeType }
     *     
     */
    public ReleaseReasonTypeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReleaseReasonTypeType }
     *     
     */
    public void setType(ReleaseReasonTypeType value) {
        this.type = value;
    }

    /**
     * Gets the value of the loc property.
     * 
     * @return
     *     possible object is
     *     {@link ReleaseLocationType }
     *     
     */
    public ReleaseLocationType getLoc() {
        return loc;
    }

    /**
     * Sets the value of the loc property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReleaseLocationType }
     *     
     */
    public void setLoc(ReleaseLocationType value) {
        this.loc = value;
    }

}
