//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReleaseLocationType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ReleaseLocationType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="u"/>
 *     &lt;enumeration value="lpn"/>
 *     &lt;enumeration value="ln"/>
 *     &lt;enumeration value="tn"/>
 *     &lt;enumeration value="rln"/>
 *     &lt;enumeration value="rpn"/>
 *     &lt;enumeration value="intl"/>
 *     &lt;enumeration value="bi"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ReleaseLocationType")
@XmlEnum
public enum ReleaseLocationType {


    /**
     * User
     * 
     */
    @XmlEnumValue("u")
    U("u"),

    /**
     * Private network serving the local user.
     *           
     * 
     */
    @XmlEnumValue("lpn")
    LPN("lpn"),

    /**
     * Public network serving the local user.
     *           
     * 
     */
    @XmlEnumValue("ln")
    LN("ln"),

    /**
     * Transit network.
     *           
     * 
     */
    @XmlEnumValue("tn")
    TN("tn"),

    /**
     * Public network serving the remote user.
     *           
     * 
     */
    @XmlEnumValue("rln")
    RLN("rln"),

    /**
     * Private network serving the remote user.
     *           
     * 
     */
    @XmlEnumValue("rpn")
    RPN("rpn"),

    /**
     * International network.
     *           
     * 
     */
    @XmlEnumValue("intl")
    INTL("intl"),

    /**
     * Network beyond interworking point.
     *           
     * 
     */
    @XmlEnumValue("bi")
    BI("bi");
    private final String value;

    ReleaseLocationType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ReleaseLocationType fromValue(String v) {
        for (ReleaseLocationType c: ReleaseLocationType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
