//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SignalingTypeBasicType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SignalingTypeBasicType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ISUP"/>
 *     &lt;enumeration value="Basic SIP"/>
 *     &lt;enumeration value="SIP-T"/>
 *     &lt;enumeration value="SIP-I"/>
 *     &lt;enumeration value="SIP unknown type"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SignalingTypeBasicType")
@XmlEnum
public enum SignalingTypeBasicType {


    /**
     * The signaling type is ISUP.
     *           
     * 
     */
    ISUP("ISUP"),

    /**
     * The signaling type is Basic SIP, i.e. not SIP-T or
     *             SIP-I.
     *           
     * 
     */
    @XmlEnumValue("Basic SIP")
    BASIC_SIP("Basic SIP"),

    /**
     * The signaling type is SIP-T.
     *           
     * 
     */
    @XmlEnumValue("SIP-T")
    SIP_T("SIP-T"),

    /**
     * The signaling type is SIP-I.
     *           
     * 
     */
    @XmlEnumValue("SIP-I")
    SIP_I("SIP-I"),

    /**
     * The signaling type is SIP, of an unknwon type.
     *           
     * 
     */
    @XmlEnumValue("SIP unknown type")
    SIP_UNKNOWN_TYPE("SIP unknown type");
    private final String value;

    SignalingTypeBasicType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SignalingTypeBasicType fromValue(String v) {
        for (SignalingTypeBasicType c: SignalingTypeBasicType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
