//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Specifies information about the signaling associated with
 *         a call. Whether information is present depends on the signaling stacks
 *         used for either half of the call.
 * 
 *         Introduced: Version 1.0, Compatibility Level 2.
 *       
 * 
 * <p>Java class for SignalingInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SignalingInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ISUPPreference" type="{http://www.metaswitch.com/cfs/billing/V1.0}ISUPPreferenceType" minOccurs="0"/>
 *         &lt;element name="ISUPUsed" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="UserService" type="{http://www.metaswitch.com/cfs/billing/V1.0}UserServiceType" minOccurs="0"/>
 *         &lt;element name="FallbackUserService" type="{http://www.metaswitch.com/cfs/billing/V1.0}UserServiceType" minOccurs="0"/>
 *         &lt;element name="MediaCapabilityRequested" type="{http://www.metaswitch.com/cfs/billing/V1.0}MediaCapabilityType" minOccurs="0"/>
 *         &lt;element name="MediaCapabilityUsed" type="{http://www.metaswitch.com/cfs/billing/V1.0}MediaCapabilityType" minOccurs="0"/>
 *         &lt;element name="Peer" type="{http://www.metaswitch.com/cfs/billing/V1.0}PeerType" maxOccurs="2" minOccurs="0"/>
 *         &lt;element name="DestinationPointCode" type="{http://www.metaswitch.com/cfs/billing/V1.0}PointCodeType" minOccurs="0"/>
 *         &lt;element name="UUIMessages" type="{http://www.metaswitch.com/cfs/billing/V1.0}UUIServicesType" minOccurs="0"/>
 *         &lt;element name="ChargeIndicator" type="{http://www.metaswitch.com/cfs/billing/V1.0}ChargeIndicatorType" minOccurs="0"/>
 *         &lt;element name="CalledPartyNumCat" type="{http://www.metaswitch.com/cfs/billing/V1.0}CalledPartyNumCat" minOccurs="0"/>
 *         &lt;element name="BearerCapability" type="{http://www.metaswitch.com/cfs/billing/V1.0}BearerCapabilityType" minOccurs="0"/>
 *         &lt;element name="SatelliteIndicator" type="{http://www.metaswitch.com/cfs/billing/V1.0}SatelliteIndicatorType" minOccurs="0"/>
 *         &lt;element name="EchoControlInfo" type="{http://www.metaswitch.com/cfs/billing/V1.0}EchoControlInfoType" minOccurs="0"/>
 *         &lt;element name="Announcement" type="{http://www.metaswitch.com/cfs/billing/V1.0}AnnouncementType" minOccurs="0"/>
 *         &lt;element name="CallReference" type="{http://www.metaswitch.com/cfs/billing/V1.0}CallReferenceType" minOccurs="0"/>
 *         &lt;element name="PChargingVector" type="{http://www.metaswitch.com/cfs/billing/V1.0}PChargingVectorType" minOccurs="0"/>
 *         &lt;element name="PVisitedNetworkId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PChargingFunctionAddresses" type="{http://www.metaswitch.com/cfs/billing/V1.0}PChargingFunctionAddressesType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignalingInfoType", propOrder = {
    "isupPreference",
    "isupUsed",
    "userService",
    "fallbackUserService",
    "mediaCapabilityRequested",
    "mediaCapabilityUsed",
    "peer",
    "destinationPointCode",
    "uuiMessages",
    "chargeIndicator",
    "calledPartyNumCat",
    "bearerCapability",
    "satelliteIndicator",
    "echoControlInfo",
    "announcement",
    "callReference",
    "pChargingVector",
    "pVisitedNetworkId",
    "pChargingFunctionAddresses"
})
public class SignalingInfoType {

    @XmlElement(name = "ISUPPreference")
    protected Short isupPreference;
    @XmlElement(name = "ISUPUsed")
    protected Boolean isupUsed;
    @XmlElement(name = "UserService")
    protected UserServiceType userService;
    @XmlElement(name = "FallbackUserService")
    protected UserServiceType fallbackUserService;
    @XmlElement(name = "MediaCapabilityRequested")
    protected String mediaCapabilityRequested;
    @XmlElement(name = "MediaCapabilityUsed")
    protected String mediaCapabilityUsed;
    @XmlElement(name = "Peer")
    protected List<PeerType> peer;
    @XmlElement(name = "DestinationPointCode")
    protected Integer destinationPointCode;
    @XmlElement(name = "UUIMessages")
    protected UUIServicesType uuiMessages;
    @XmlElement(name = "ChargeIndicator")
    protected ChargeIndicatorType chargeIndicator;
    @XmlElement(name = "CalledPartyNumCat")
    protected CalledPartyNumCat calledPartyNumCat;
    @XmlElement(name = "BearerCapability")
    protected String bearerCapability;
    @XmlElement(name = "SatelliteIndicator")
    protected SatelliteIndicatorType satelliteIndicator;
    @XmlElement(name = "EchoControlInfo")
    protected EchoControlInfoType echoControlInfo;
    @XmlElement(name = "Announcement")
    protected AnnouncementType announcement;
    @XmlElement(name = "CallReference")
    protected CallReferenceType callReference;
    @XmlElement(name = "PChargingVector")
    protected PChargingVectorType pChargingVector;
    @XmlElement(name = "PVisitedNetworkId")
    protected String pVisitedNetworkId;
    @XmlElement(name = "PChargingFunctionAddresses")
    protected PChargingFunctionAddressesType pChargingFunctionAddresses;

    /**
     * Gets the value of the isupPreference property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public Short getISUPPreference() {
        return isupPreference;
    }

    /**
     * Sets the value of the isupPreference property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setISUPPreference(Short value) {
        this.isupPreference = value;
    }

    /**
     * Gets the value of the isupUsed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isISUPUsed() {
        return isupUsed;
    }

    /**
     * Sets the value of the isupUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setISUPUsed(Boolean value) {
        this.isupUsed = value;
    }

    /**
     * Gets the value of the userService property.
     * 
     * @return
     *     possible object is
     *     {@link UserServiceType }
     *     
     */
    public UserServiceType getUserService() {
        return userService;
    }

    /**
     * Sets the value of the userService property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserServiceType }
     *     
     */
    public void setUserService(UserServiceType value) {
        this.userService = value;
    }

    /**
     * Gets the value of the fallbackUserService property.
     * 
     * @return
     *     possible object is
     *     {@link UserServiceType }
     *     
     */
    public UserServiceType getFallbackUserService() {
        return fallbackUserService;
    }

    /**
     * Sets the value of the fallbackUserService property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserServiceType }
     *     
     */
    public void setFallbackUserService(UserServiceType value) {
        this.fallbackUserService = value;
    }

    /**
     * Gets the value of the mediaCapabilityRequested property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMediaCapabilityRequested() {
        return mediaCapabilityRequested;
    }

    /**
     * Sets the value of the mediaCapabilityRequested property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMediaCapabilityRequested(String value) {
        this.mediaCapabilityRequested = value;
    }

    /**
     * Gets the value of the mediaCapabilityUsed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMediaCapabilityUsed() {
        return mediaCapabilityUsed;
    }

    /**
     * Sets the value of the mediaCapabilityUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMediaCapabilityUsed(String value) {
        this.mediaCapabilityUsed = value;
    }

    /**
     * Gets the value of the peer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the peer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPeer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PeerType }
     * 
     * 
     */
    public List<PeerType> getPeer() {
        if (peer == null) {
            peer = new ArrayList<PeerType>();
        }
        return this.peer;
    }

    /**
     * Gets the value of the destinationPointCode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDestinationPointCode() {
        return destinationPointCode;
    }

    /**
     * Sets the value of the destinationPointCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDestinationPointCode(Integer value) {
        this.destinationPointCode = value;
    }

    /**
     * Gets the value of the uuiMessages property.
     * 
     * @return
     *     possible object is
     *     {@link UUIServicesType }
     *     
     */
    public UUIServicesType getUUIMessages() {
        return uuiMessages;
    }

    /**
     * Sets the value of the uuiMessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link UUIServicesType }
     *     
     */
    public void setUUIMessages(UUIServicesType value) {
        this.uuiMessages = value;
    }

    /**
     * Gets the value of the chargeIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link ChargeIndicatorType }
     *     
     */
    public ChargeIndicatorType getChargeIndicator() {
        return chargeIndicator;
    }

    /**
     * Sets the value of the chargeIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChargeIndicatorType }
     *     
     */
    public void setChargeIndicator(ChargeIndicatorType value) {
        this.chargeIndicator = value;
    }

    /**
     * Gets the value of the calledPartyNumCat property.
     * 
     * @return
     *     possible object is
     *     {@link CalledPartyNumCat }
     *     
     */
    public CalledPartyNumCat getCalledPartyNumCat() {
        return calledPartyNumCat;
    }

    /**
     * Sets the value of the calledPartyNumCat property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalledPartyNumCat }
     *     
     */
    public void setCalledPartyNumCat(CalledPartyNumCat value) {
        this.calledPartyNumCat = value;
    }

    /**
     * Gets the value of the bearerCapability property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBearerCapability() {
        return bearerCapability;
    }

    /**
     * Sets the value of the bearerCapability property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBearerCapability(String value) {
        this.bearerCapability = value;
    }

    /**
     * Gets the value of the satelliteIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link SatelliteIndicatorType }
     *     
     */
    public SatelliteIndicatorType getSatelliteIndicator() {
        return satelliteIndicator;
    }

    /**
     * Sets the value of the satelliteIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link SatelliteIndicatorType }
     *     
     */
    public void setSatelliteIndicator(SatelliteIndicatorType value) {
        this.satelliteIndicator = value;
    }

    /**
     * Gets the value of the echoControlInfo property.
     * 
     * @return
     *     possible object is
     *     {@link EchoControlInfoType }
     *     
     */
    public EchoControlInfoType getEchoControlInfo() {
        return echoControlInfo;
    }

    /**
     * Sets the value of the echoControlInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link EchoControlInfoType }
     *     
     */
    public void setEchoControlInfo(EchoControlInfoType value) {
        this.echoControlInfo = value;
    }

    /**
     * Gets the value of the announcement property.
     * 
     * @return
     *     possible object is
     *     {@link AnnouncementType }
     *     
     */
    public AnnouncementType getAnnouncement() {
        return announcement;
    }

    /**
     * Sets the value of the announcement property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnouncementType }
     *     
     */
    public void setAnnouncement(AnnouncementType value) {
        this.announcement = value;
    }

    /**
     * Gets the value of the callReference property.
     * 
     * @return
     *     possible object is
     *     {@link CallReferenceType }
     *     
     */
    public CallReferenceType getCallReference() {
        return callReference;
    }

    /**
     * Sets the value of the callReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link CallReferenceType }
     *     
     */
    public void setCallReference(CallReferenceType value) {
        this.callReference = value;
    }

    /**
     * Gets the value of the pChargingVector property.
     * 
     * @return
     *     possible object is
     *     {@link PChargingVectorType }
     *     
     */
    public PChargingVectorType getPChargingVector() {
        return pChargingVector;
    }

    /**
     * Sets the value of the pChargingVector property.
     * 
     * @param value
     *     allowed object is
     *     {@link PChargingVectorType }
     *     
     */
    public void setPChargingVector(PChargingVectorType value) {
        this.pChargingVector = value;
    }

    /**
     * Gets the value of the pVisitedNetworkId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPVisitedNetworkId() {
        return pVisitedNetworkId;
    }

    /**
     * Sets the value of the pVisitedNetworkId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPVisitedNetworkId(String value) {
        this.pVisitedNetworkId = value;
    }

    /**
     * Gets the value of the pChargingFunctionAddresses property.
     * 
     * @return
     *     possible object is
     *     {@link PChargingFunctionAddressesType }
     *     
     */
    public PChargingFunctionAddressesType getPChargingFunctionAddresses() {
        return pChargingFunctionAddresses;
    }

    /**
     * Sets the value of the pChargingFunctionAddresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link PChargingFunctionAddressesType }
     *     
     */
    public void setPChargingFunctionAddresses(PChargingFunctionAddressesType value) {
        this.pChargingFunctionAddresses = value;
    }

}
