//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrunkTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TrunkTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="no sig"/>
 *     &lt;enumeration value="isup"/>
 *     &lt;enumeration value="analog line"/>
 *     &lt;enumeration value="call services"/>
 *     &lt;enumeration value="mf"/>
 *     &lt;enumeration value="isdn"/>
 *     &lt;enumeration value="sip"/>
 *     &lt;enumeration value="none"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TrunkTypeType")
@XmlEnum
public enum TrunkTypeType {


    /**
     * No signaling associated with this trunk.
     *           
     * 
     */
    @XmlEnumValue("no sig")
    NO_SIG("no sig"),

    /**
     * An ISUP trunk.
     *           
     * 
     */
    @XmlEnumValue("isup")
    ISUP("isup"),

    /**
     * An individual analog line - this value is not expected
     *             in CDRs.
     *           
     * 
     */
    @XmlEnumValue("analog line")
    ANALOG_LINE("analog line"),

    /**
     * A call service - this value is not expected in CDRs.
     *           
     * 
     */
    @XmlEnumValue("call services")
    CALL_SERVICES("call services"),

    /**
     * An MF trunk.
     *           
     * 
     */
    @XmlEnumValue("mf")
    MF("mf"),

    /**
     * An ISDN PRI trunk.
     *           
     * 
     */
    @XmlEnumValue("isdn")
    ISDN("isdn"),

    /**
     * A SIP trunk.
     *           
     * 
     */
    @XmlEnumValue("sip")
    SIP("sip"),

    /**
     * No signalling associated with this trunk.
     *           
     * 
     */
    @XmlEnumValue("none")
    NONE("none");
    private final String value;

    TrunkTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TrunkTypeType fromValue(String v) {
        for (TrunkTypeType c: TrunkTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
