//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Represents a trunk routing failure reason, which
 *         may be one of a Q.850 release cause, a SIP response code or an internal
 *         "skip" reason code.
 * 
 * <p>Java class for TrunkFailReasonType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrunkFailReasonType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.metaswitch.com/cfs/billing/V1.0>TrunkFailReasonsType">
 *       &lt;attribute name="type" use="required" type="{http://www.metaswitch.com/cfs/billing/V1.0}TrunkFailTypeType" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrunkFailReasonType", propOrder = {
    "value"
})
public class TrunkFailReasonType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "type", required = true)
    protected TrunkFailTypeType type;

    /**
     * The reasons that a trunk may have failed to route a call.
     *         the trunk may have been skipped, or may have failed having been
     *         selected.
     *       
     * 
     * The trunk may have been skipped (SkipReasonType) or have
     *           failed after selection (Q850ReasonType or SIPReasonType).
     *         
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link TrunkFailTypeType }
     *     
     */
    public TrunkFailTypeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrunkFailTypeType }
     *     
     */
    public void setType(TrunkFailTypeType value) {
        this.type = value;
    }

}
