//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TrunkFailTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TrunkFailTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="q850"/>
 *     &lt;enumeration value="sip"/>
 *     &lt;enumeration value="skip"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TrunkFailTypeType")
@XmlEnum
public enum TrunkFailTypeType {


    /**
     * The reason is a Q.850 Cause value. Interpret as a
     *             Q850ReasonType.
     *           
     * 
     */
    @XmlEnumValue("q850")
    Q_850("q850"),

    /**
     * The reason is a SIP release cause. Interpret as a
     *           SIPReasonType.
     * 
     */
    @XmlEnumValue("sip")
    SIP("sip"),

    /**
     * The reason is an internal MetaSphere value. Interpret
     *           as a SkipReasonType.
     *           
     * 
     */
    @XmlEnumValue("skip")
    SKIP("skip");
    private final String value;

    TrunkFailTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TrunkFailTypeType fromValue(String v) {
        for (TrunkFailTypeType c: TrunkFailTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
