//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Specifies information about the signaling associated with
 *         a User-User Information service.
 * 
 *         Introduced: Version 1.0, Compatibility Level 2.
 *       
 * 
 * <p>Java class for UUIServiceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UUIServiceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Forwards" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="Backwards" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UUIServiceType", propOrder = {
    "forwards",
    "backwards"
})
public class UUIServiceType {

    @XmlElement(name = "Forwards")
    @XmlSchemaType(name = "unsignedInt")
    protected Long forwards;
    @XmlElement(name = "Backwards")
    @XmlSchemaType(name = "unsignedInt")
    protected Long backwards;

    /**
     * Gets the value of the forwards property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getForwards() {
        return forwards;
    }

    /**
     * Sets the value of the forwards property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setForwards(Long value) {
        this.forwards = value;
    }

    /**
     * Gets the value of the backwards property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getBackwards() {
        return backwards;
    }

    /**
     * Sets the value of the backwards property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setBackwards(Long value) {
        this.backwards = value;
    }

}
