//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Specifies information about the signaling associated with
 *         the User-User Information services (UUI1, UUI2 and UUI3).
 * 
 *         Introduced: Version 1.0, Compatibility Level 2.
 *       
 * 
 * <p>Java class for UUIServicesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UUIServicesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UUI1" type="{http://www.metaswitch.com/cfs/billing/V1.0}UUIServiceType" minOccurs="0"/>
 *         &lt;element name="UUI2" type="{http://www.metaswitch.com/cfs/billing/V1.0}UUIServiceType" minOccurs="0"/>
 *         &lt;element name="UUI3" type="{http://www.metaswitch.com/cfs/billing/V1.0}UUIServiceType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UUIServicesType", propOrder = {
    "uui1",
    "uui2",
    "uui3"
})
public class UUIServicesType {

    @XmlElement(name = "UUI1")
    protected UUIServiceType uui1;
    @XmlElement(name = "UUI2")
    protected UUIServiceType uui2;
    @XmlElement(name = "UUI3")
    protected UUIServiceType uui3;

    /**
     * Gets the value of the uui1 property.
     * 
     * @return
     *     possible object is
     *     {@link UUIServiceType }
     *     
     */
    public UUIServiceType getUUI1() {
        return uui1;
    }

    /**
     * Sets the value of the uui1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link UUIServiceType }
     *     
     */
    public void setUUI1(UUIServiceType value) {
        this.uui1 = value;
    }

    /**
     * Gets the value of the uui2 property.
     * 
     * @return
     *     possible object is
     *     {@link UUIServiceType }
     *     
     */
    public UUIServiceType getUUI2() {
        return uui2;
    }

    /**
     * Sets the value of the uui2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link UUIServiceType }
     *     
     */
    public void setUUI2(UUIServiceType value) {
        this.uui2 = value;
    }

    /**
     * Gets the value of the uui3 property.
     * 
     * @return
     *     possible object is
     *     {@link UUIServiceType }
     *     
     */
    public UUIServiceType getUUI3() {
        return uui3;
    }

    /**
     * Sets the value of the uui3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link UUIServiceType }
     *     
     */
    public void setUUI3(UUIServiceType value) {
        this.uui3 = value;
    }

}
