//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines VQM delay stats
 * 
 * <p>Java class for VQMCallQualityStatsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VQMCallQualityStatsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RFactor" type="{http://www.metaswitch.com/cfs/billing/V1.0}RFactorType" minOccurs="0"/>
 *         &lt;element name="ExternalRFactor" type="{http://www.metaswitch.com/cfs/billing/V1.0}RFactorType" minOccurs="0"/>
 *         &lt;element name="LQMos" type="{http://www.metaswitch.com/cfs/billing/V1.0}MOSType" minOccurs="0"/>
 *         &lt;element name="CQMos" type="{http://www.metaswitch.com/cfs/billing/V1.0}MOSType" minOccurs="0"/>
 *         &lt;element name="OverallRFactor" type="{http://www.metaswitch.com/cfs/billing/V1.0}OverallRFactorType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VQMCallQualityStatsType", propOrder = {
    "rFactor",
    "externalRFactor",
    "lqMos",
    "cqMos",
    "overallRFactor"
})
public class VQMCallQualityStatsType {

    @XmlElement(name = "RFactor")
    protected Integer rFactor;
    @XmlElement(name = "ExternalRFactor")
    protected Integer externalRFactor;
    @XmlElement(name = "LQMos")
    protected Integer lqMos;
    @XmlElement(name = "CQMos")
    protected Integer cqMos;
    @XmlElement(name = "OverallRFactor")
    protected Integer overallRFactor;

    /**
     * Gets the value of the rFactor property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRFactor() {
        return rFactor;
    }

    /**
     * Sets the value of the rFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRFactor(Integer value) {
        this.rFactor = value;
    }

    /**
     * Gets the value of the externalRFactor property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getExternalRFactor() {
        return externalRFactor;
    }

    /**
     * Sets the value of the externalRFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setExternalRFactor(Integer value) {
        this.externalRFactor = value;
    }

    /**
     * Gets the value of the lqMos property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLQMos() {
        return lqMos;
    }

    /**
     * Sets the value of the lqMos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLQMos(Integer value) {
        this.lqMos = value;
    }

    /**
     * Gets the value of the cqMos property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCQMos() {
        return cqMos;
    }

    /**
     * Sets the value of the cqMos property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCQMos(Integer value) {
        this.cqMos = value;
    }

    /**
     * Gets the value of the overallRFactor property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getOverallRFactor() {
        return overallRFactor;
    }

    /**
     * Sets the value of the overallRFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setOverallRFactor(Integer value) {
        this.overallRFactor = value;
    }

}
