//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines VQM packet stats
 * 
 * <p>Java class for VQMPacketStatsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VQMPacketStatsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Sent" type="{http://www.metaswitch.com/cfs/billing/V1.0}PacketCountType" minOccurs="0"/>
 *         &lt;element name="Received" type="{http://www.metaswitch.com/cfs/billing/V1.0}PacketCountType" minOccurs="0"/>
 *         &lt;element name="LossRate" type="{http://www.metaswitch.com/cfs/billing/V1.0}PacketLossRateType" minOccurs="0"/>
 *         &lt;element name="Discarded" type="{http://www.metaswitch.com/cfs/billing/V1.0}PacketCountType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VQMPacketStatsType", propOrder = {
    "sent",
    "received",
    "lossRate",
    "discarded"
})
public class VQMPacketStatsType {

    @XmlElement(name = "Sent")
    protected BigInteger sent;
    @XmlElement(name = "Received")
    protected BigInteger received;
    @XmlElement(name = "LossRate")
    protected BigDecimal lossRate;
    @XmlElement(name = "Discarded")
    protected BigInteger discarded;

    /**
     * Gets the value of the sent property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSent() {
        return sent;
    }

    /**
     * Sets the value of the sent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSent(BigInteger value) {
        this.sent = value;
    }

    /**
     * Gets the value of the received property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReceived() {
        return received;
    }

    /**
     * Sets the value of the received property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReceived(BigInteger value) {
        this.received = value;
    }

    /**
     * Gets the value of the lossRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLossRate() {
        return lossRate;
    }

    /**
     * Sets the value of the lossRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLossRate(BigDecimal value) {
        this.lossRate = value;
    }

    /**
     * Gets the value of the discarded property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDiscarded() {
        return discarded;
    }

    /**
     * Sets the value of the discarded property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDiscarded(BigInteger value) {
        this.discarded = value;
    }

}
