//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines the VQM stats for a termination - i.e. for a
 *         TAG or an endpoint.
 *       
 * 
 * <p>Java class for VQMTermStatsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VQMTermStatsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Octets" type="{http://www.metaswitch.com/cfs/billing/V1.0}VQMOctetStatsType" minOccurs="0"/>
 *         &lt;element name="Packets" type="{http://www.metaswitch.com/cfs/billing/V1.0}VQMPacketStatsType" minOccurs="0"/>
 *         &lt;element name="Jitter" type="{http://www.metaswitch.com/cfs/billing/V1.0}JitterType" minOccurs="0"/>
 *         &lt;element name="Delay" type="{http://www.metaswitch.com/cfs/billing/V1.0}VQMDelayStatsType" minOccurs="0"/>
 *         &lt;element name="CallQuality" type="{http://www.metaswitch.com/cfs/billing/V1.0}VQMCallQualityStatsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VQMTermStatsType", propOrder = {
    "octets",
    "packets",
    "jitter",
    "delay",
    "callQuality"
})
public class VQMTermStatsType {

    @XmlElement(name = "Octets")
    protected VQMOctetStatsType octets;
    @XmlElement(name = "Packets")
    protected VQMPacketStatsType packets;
    @XmlElement(name = "Jitter")
    protected String jitter;
    @XmlElement(name = "Delay")
    protected VQMDelayStatsType delay;
    @XmlElement(name = "CallQuality")
    protected VQMCallQualityStatsType callQuality;

    /**
     * Gets the value of the octets property.
     * 
     * @return
     *     possible object is
     *     {@link VQMOctetStatsType }
     *     
     */
    public VQMOctetStatsType getOctets() {
        return octets;
    }

    /**
     * Sets the value of the octets property.
     * 
     * @param value
     *     allowed object is
     *     {@link VQMOctetStatsType }
     *     
     */
    public void setOctets(VQMOctetStatsType value) {
        this.octets = value;
    }

    /**
     * Gets the value of the packets property.
     * 
     * @return
     *     possible object is
     *     {@link VQMPacketStatsType }
     *     
     */
    public VQMPacketStatsType getPackets() {
        return packets;
    }

    /**
     * Sets the value of the packets property.
     * 
     * @param value
     *     allowed object is
     *     {@link VQMPacketStatsType }
     *     
     */
    public void setPackets(VQMPacketStatsType value) {
        this.packets = value;
    }

    /**
     * Gets the value of the jitter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJitter() {
        return jitter;
    }

    /**
     * Sets the value of the jitter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJitter(String value) {
        this.jitter = value;
    }

    /**
     * Gets the value of the delay property.
     * 
     * @return
     *     possible object is
     *     {@link VQMDelayStatsType }
     *     
     */
    public VQMDelayStatsType getDelay() {
        return delay;
    }

    /**
     * Sets the value of the delay property.
     * 
     * @param value
     *     allowed object is
     *     {@link VQMDelayStatsType }
     *     
     */
    public void setDelay(VQMDelayStatsType value) {
        this.delay = value;
    }

    /**
     * Gets the value of the callQuality property.
     * 
     * @return
     *     possible object is
     *     {@link VQMCallQualityStatsType }
     *     
     */
    public VQMCallQualityStatsType getCallQuality() {
        return callQuality;
    }

    /**
     * Sets the value of the callQuality property.
     * 
     * @param value
     *     allowed object is
     *     {@link VQMCallQualityStatsType }
     *     
     */
    public void setCallQuality(VQMCallQualityStatsType value) {
        this.callQuality = value;
    }

}
