//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 11:04:31 AM AEST 
//


package javalearning.xml.cfs;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines the VQM stats for a party in a call.  Each party
 *         can have different statistics.
 *       
 * 
 * <p>Java class for VQMType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VQMType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Endpoint" type="{http://www.metaswitch.com/cfs/billing/V1.0}VQMTermStatsType" minOccurs="0"/>
 *         &lt;element name="TAG" type="{http://www.metaswitch.com/cfs/billing/V1.0}VQMTermStatsType" minOccurs="0"/>
 *         &lt;element name="Codec" type="{http://www.metaswitch.com/cfs/billing/V1.0}CodecType" minOccurs="0"/>
 *         &lt;element name="Codecs" type="{http://www.metaswitch.com/cfs/billing/V1.0}CodecsType" minOccurs="0"/>
 *         &lt;element name="RoundTripDelay" type="{http://www.metaswitch.com/cfs/billing/V1.0}DelayType" minOccurs="0"/>
 *         &lt;element name="DetectedFaxTone" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VQMType", propOrder = {
    "endpoint",
    "tag",
    "codec",
    "codecs",
    "roundTripDelay",
    "detectedFaxTone"
})
public class VQMType {

    @XmlElement(name = "Endpoint")
    protected VQMTermStatsType endpoint;
    @XmlElement(name = "TAG")
    protected VQMTermStatsType tag;
    @XmlElement(name = "Codec")
    protected CodecType codec;
    @XmlElement(name = "Codecs")
    protected CodecsType codecs;
    @XmlElement(name = "RoundTripDelay")
    protected String roundTripDelay;
    @XmlElement(name = "DetectedFaxTone")
    protected Boolean detectedFaxTone;

    /**
     * Gets the value of the endpoint property.
     * 
     * @return
     *     possible object is
     *     {@link VQMTermStatsType }
     *     
     */
    public VQMTermStatsType getEndpoint() {
        return endpoint;
    }

    /**
     * Sets the value of the endpoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link VQMTermStatsType }
     *     
     */
    public void setEndpoint(VQMTermStatsType value) {
        this.endpoint = value;
    }

    /**
     * Gets the value of the tag property.
     * 
     * @return
     *     possible object is
     *     {@link VQMTermStatsType }
     *     
     */
    public VQMTermStatsType getTAG() {
        return tag;
    }

    /**
     * Sets the value of the tag property.
     * 
     * @param value
     *     allowed object is
     *     {@link VQMTermStatsType }
     *     
     */
    public void setTAG(VQMTermStatsType value) {
        this.tag = value;
    }

    /**
     * Gets the value of the codec property.
     * 
     * @return
     *     possible object is
     *     {@link CodecType }
     *     
     */
    public CodecType getCodec() {
        return codec;
    }

    /**
     * Sets the value of the codec property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodecType }
     *     
     */
    public void setCodec(CodecType value) {
        this.codec = value;
    }

    /**
     * Gets the value of the codecs property.
     * 
     * @return
     *     possible object is
     *     {@link CodecsType }
     *     
     */
    public CodecsType getCodecs() {
        return codecs;
    }

    /**
     * Sets the value of the codecs property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodecsType }
     *     
     */
    public void setCodecs(CodecsType value) {
        this.codecs = value;
    }

    /**
     * Gets the value of the roundTripDelay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoundTripDelay() {
        return roundTripDelay;
    }

    /**
     * Sets the value of the roundTripDelay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoundTripDelay(String value) {
        this.roundTripDelay = value;
    }

    /**
     * Gets the value of the detectedFaxTone property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDetectedFaxTone() {
        return detectedFaxTone;
    }

    /**
     * Sets the value of the detectedFaxTone property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDetectedFaxTone(Boolean value) {
        this.detectedFaxTone = value;
    }

}
